### ISSUE TITLE
RocketLoader Does not Run

### ISSUE THREAD

**Issue by MasterCreate66** [RocketFoundation/Rocket#1]
The following screen appears after I start Rocket Loader. I think I might not have the right .net version
![untitled](https://cloud.githubusercontent.com/assets/6993228/5770548/ec09862a-9cf9-11e4-86d3-09db00223e0b.png)

**Comment by fr34kyn01535** [comment]
Can not reproduce, is Unturned running while you try to patch?

**Comment by MasterCreate66** [comment]
No. Unturned is not running. I tried a fresh install with Steam CMD. Im running windows server 2008 btw. I might just patch it on my home computer and FTP it over to the server. I'll try that tonight

**Comment by MasterCreate66** [comment]
Got it working. It had to do with the way I had my security settings set up on my Windows Server

**Comment by fr34kyn01535** [comment]
Could you explain how you fixed it? Btw. this problem does not occur in a Windows Server 2012 default setup.

**Comment by MasterCreate66** [comment]
It was the .net framework version I was running. I updated it the other day and RocketLoader seemed to work xD
