### ISSUE TITLE
Automated server messages broken

### ISSUE THREAD

**Issue by JohnnyChimpo420** [RocketFoundation/Rocket#101]
All automated server messages i.e; Message Announcer, Feast announcements, connecting and disconnecting messages, and I haven't checked on this one yet but i am sure the auto shutdown messages are showing up in a dark blue and not displaying the correct information.

**Comment by ZSHADOWWOLF** [comment]
All messages from the server are issued with incorrect display of nicknames,unknown characters and painted in dark blue waiting for the fix to play is not very convenient

**Comment by UntVicioStudios** [comment]
Messages displaying even worse in latin languages.

**Comment by ZSHADOWWOLF** [comment]
All not using the right hands is done....Need Hotfix....And the sooner the better

**Comment by mryan04290** [comment]
i have a screen shot too
http://prntscr.com/761230
thats the link

**Comment by fr34kyn01535** [comment]
Its a rocket issue...

**Comment by Zamirathe** [comment]
Should be all fixed now in Rocket 3.9.2.4.
