### ISSUE TITLE
Latest Rocket Version v4.0.0.0 is not loading Plugins.

### ISSUE THREAD

**Issue by lightphoenix2** [RocketFoundation/Rocket#104]
Plugins of the server is not loaded and it wasn't display on the console or log. Players complain that they can't use any command due for those plugins.

**Comment by fr34kyn01535** [comment]
Your plugins probably broke, Rocket 4 has changed drastically. https://rocket.foundation/viewtopic.php?f=44&t=272&p=866#p866

**Comment by lightphoenix2** [comment]
All of my plugin broke?

**Comment by lightphoenix2** [comment]
Indeed, the plugin all broke.

**Comment by fr34kyn01535** [comment]
Thank you for reading my answer.

**Comment by lightphoenix2** [comment]
Why is the Alert:Server is in white colour, which is different from its usual green?

**Comment by lightphoenix2** [comment]
I saw the new update. Phew* its so much easier to use /say or "say" in console. No longer have to type /say Hi/0/240/0
