### ISSUE TITLE
New Rocket update

### ISSUE THREAD

**Issue by bernas293** [RocketFoundation/Rocket#110]
Can you see if im doing anything wrong? 

since i modify the reserverd slots and pass false to true in Joinandleavingsms the server give me a error

http://pastebin.com/3i9zbsh8

please check my configs, or it is a bug? 

The error 

[IMG]http://i62.tinypic.com/n5jvci.png[/IMG]

**Comment by cartman-2000** [comment]
That trace is coming from the text commands plugin, not the rocket config file. Has this plugin been updated for rocket 4.0 yet? It would need to be for it to work.

**Comment by Zamirathe** [comment]
Yes it has been.

**Comment by bernas293** [comment]
so what i have to do?

**Comment by Zamirathe** [comment]
You need to download the latest version of the text commands plugin.

**Comment by bernas293** [comment]
I did that and the problem stilss remaining :S this error only appear when e i change the rocket config, because when i dont nothing happens, i have all my pluguins upadated with yours lats configs to rocket 4.0... so i dunno what is the problem... because when i dont make any change in the rocket config, there is no error! everything fine, but when i chage false to true or the reserverd slots so the error apears

look at this when i dont make any change on rocket config : no error, everything fine

http://i62.tinypic.com/fnb8ef.png

**Comment by bernas293** [comment]
problem solved with new rocket upadte
