### ISSUE TITLE
say Command

### ISSUE THREAD

**Issue by lightphoenix2** [RocketFoundation/Rocket#111]
Unable to type message containing "/". For example if I need to tell someone, I type "You need to type /rule or /help" But I can't do that anymore.

**Comment by cartman-2000** [comment]
Not really a rocket bug, the say command is in built in command, and it was modified, in the most recent update to unturned, to allow colors to be used on the command, but that means that you can no longer put anything in the command to say that contains a slash.

**Comment by fr34kyn01535** [comment]
Added broadcast to prevent this, syntax is /broadcast "My Message" red

**Comment by lightphoenix2** [comment]
fr34kyn01535 can you put config to have a default RGB vaule for the text?
