### ISSUE TITLE
Server won't read my Plugins.

### ISSUE THREAD

**Issue by LeeIzaZombie** [RocketFoundation/Rocket#112]
I've updated my Plugins from looking at the changelog prior to Rocket 4.0.
Here are my usings:
using System;
using UnityEngine;
using System.IO;
using System.Timers;
using System.Threading;
using System.Diagnostics;
using System.Collections.Generic;
using Rocket.Core;
using Rocket.Commands;
using Rocket.API;
using Rocket.Components;
using Rocket.Logging;
using Rocket.RCON;
using Rocket.RocketAPI;
using Rocket.Unturned;

I've applied all the changes from the changelog, no errors when I compile. When I load the server it just completely ignores the Plugin, no errors... nothing.

**Comment by cartman-2000** [comment]
Have you forgotten to remove the old reference to the RocketAPI.dll file in the project? Rocket.Commands, Rocket.Components, Rocket.Logging, Rocket.RCON and Rocket.RocketAPI don't exist at those name spaces in the newest builds of rocket.

**Comment by fr34kyn01535** [comment]
Don't import RocketAPI.
Read https://rocket.foundation/viewtopic.php?f=44&t=272 please
