### ISSUE TITLE
System Null Reference Exception

### ISSUE THREAD

**Issue by bman1248** [RocketFoundation/Rocket#113]
When the server is started up it starts up normal when a players loads into the server this error appears and loops

http://puu.sh/hQBUc/9aa16f46a8.png

**Comment by fr34kyn01535** [comment]
Does that still appear in latest Rocket? I think i fixed it.

**Comment by bman1248** [comment]
the error is still appearing in troves in the most recent beta build

**Comment by bman1248** [comment]
not sure if this is useful but this is the error that appears after the server starts and before players joined 
http://pastebin.com/U8NyTBWv

**Comment by fr34kyn01535** [comment]
Thats not the same error -.-

**Comment by fr34kyn01535** [comment]
Its an outdated MessageAnnouncer

**Comment by bman1248** [comment]
http://puu.sh/hRiEP/86e3df6e08.png this is the error appearing now

**Comment by Zamirathe** [comment]
Right before this error starts what happens?

**Comment by bman1248** [comment]
when a player joins

**Comment by bman1248** [comment]
it was one of the plugins causing the error not rocket
