### ISSUE TITLE
Home button suggestion

### ISSUE THREAD

**Issue by CynicalSinner91** [RocketFoundation/Rocket#115]
On my current server we have notice a minor issue and have a suggestion for it. The issue occurs when lets say there is a group holding down a certain area like the military base and have a bed hidden near where they are camping like towers. Now the problem is that with no delay on the home button to revive at their bed they can instantly come back and recollect their loot rather then having to wait a short period of time. I would like to suggest a 10 - 20 second timer where you can not die then auto come back to your bed.

**Comment by fr34kyn01535** [comment]
Feel free to install a plugin that does that.

**Comment by CynicalSinner91** [comment]
the plugin that zami has made only puts a cooldown on the command /home not the physical home button
