### ISSUE TITLE
Automatic Drop players in server

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [RocketFoundation/Rocket#116]
Since I made the server I had a problem...once in a while sometimes the server discards the players with him....is corrected only by restarting the server but still this bug sometimes appears....I have this one?

**Comment by cartman-2000** [comment]
There is an unturned bug that can cause the server to refuse new connections with either the lost connection error, or the invalid auth error, in both cases the server just needs to be restarted for it to work again.

I don't think this is a bug with rocket mod, as I have had this problem off and and before I was using rocket on my server's.

**Comment by ZSHADOWWOLF** [comment]
With the latest update it started to happen more often...3-4 times every minute from 2 to 5
