### ISSUE TITLE
Color not working on RocketChat with RocketPlayer ([Alert])

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#119]
**This is always showing white, despite the color:**
*public static void Say(RocketPlayer player, string message, Color color);*

( tested with RocketChat.Say([ApokPT], "Hello World!", RocketChat.GetColorFromHex("#d7542C") );

**But this one is changing color correctly:**
*public static void Say(string message, Color color);*

**I have not tested this one:**
*public static void Say(CSteamID CSteamID, string message, Color color);*

**Comment by fr34kyn01535** [comment]
Fixed
