### ISSUE TITLE
No one Can connect after updated for V 3.10.3.1 

### ISSUE THREAD

**Issue by Thorgon-cross** [RocketFoundation/Rocket#120]
Came back after a weekend a way and update my server for 3.10.3.1 then started up the server, it loads the map but gets stuck when the load bar is at 100%.

**Comment by Zamirathe** [comment]
This is an Unturned issue and has to do with the level data.  A temporary fix is to rename/delete the Barridates.dat and Structures.dat files.  This will allow people to connect until there are too many barricades or structures again.
