### ISSUE TITLE
ArgumentOutOfRangeException: Argument is out of range. SDG.BarricadeManager.unclaimBeds

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketFoundation/Rocket#122]
![image](https://cloud.githubusercontent.com/assets/898145/7711101/9efab77a-fe68-11e4-9a05-1fa021978578.png)

**Comment by bernas293** [comment]
it happens to my server today to

**Comment by JohnnyChimpo420** [comment]
I sure hope nelson gets on this one, it is a slightly annoying bug.

**Comment by SDGNelson** [comment]
This is an important bug, but I cannot seem to replicate it. Can you provide any more information?

**Comment by JohnnyChimpo420** [comment]
@SDGNelson, firstly I love unturned, I have 500 or so hours in it, and my server is becoming quite popular. Secondly, the Argumentoutofrangeexception happens everytime someone attempts to claim a bedroll, I do not know if this is enough info for you, but anything I can do to help, I will

**Comment by JohnnyChimpo420** [comment]
It is fixed, way to go @SDGNelson!

**Comment by SDGNelson** [comment]
Awesome! I will ask Zami to mark this as closed.

**Comment by UzielTD** [comment]
The thing happens to me but it shows when player connects then players disconnects in the new unturned update
