### ISSUE TITLE
help me please? what is that?

### ISSUE THREAD

**Issue by bernas293** [RocketFoundation/Rocket#128]
[IMG]http://i59.tinypic.com/axy1ih.png[/IMG]

how i solve it?

**Comment by Zamirathe** [comment]
Don't see anything.

**Comment by cartman-2000** [comment]
By the looks of it, you may have a corrupted save on the server.

**Comment by bernas293** [comment]
problem solved, i made a reset of tha map on my server, and until now there is no problem! i dont know what have caused this...
