### ISSUE TITLE
No loot,No Zombies

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [RocketFoundation/Rocket#131]
Due to the latest update of the rocket before 4.10.4.2 on the server lost all the loot and all the zombies....why do those who make a new version of the rocket such curves hands?

**Comment by JohnnyChimpo420** [comment]
This is not a rocket bug, it is a network test being done by nelson, is testing by disabling everything and  enabling things one at a time it would seem. Early access is about bug testing unfortunately, let's be patient and wait till things are good again.

**Comment by cartman-2000** [comment]
It's in the note when you start the game up.

**Comment by bernas293** [comment]
and in my server everyone lost theys homes.... the important is we have a good game!

**Comment by Zamirathe** [comment]
Nothing has been deleted unless you delete the level data.  The game just doesn't load them in right now.

**Comment by bernas293** [comment]
nice ;)
