### ISSUE TITLE
Infinite load in server

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [RocketFoundation/Rocket#134]
I go to the server,everything is loaded,the loading screen will not retract, however I can walk,run,shoot, I can't see anything

**Comment by adam561** [comment]
Same problem here, I tried reinstalling everything.

**Comment by Zamirathe** [comment]
Your barricades file may be too big.  Rename (to backup) or delete and try again.

**Comment by fr34kyn01535** [comment]
This is a problem on the server - could be everything. As Zami mentioned there is a bug right now, if that doesn't fix your issue please provide some log files.
