### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by LazyPiggyHD** [RocketFoundation/Rocket#136]
NullReferenceException: Object reference not set to an instance of an object - S
DG.Assets.n (System.String Q, Boolean w)
SDG.Assets.n (System.String Q, Boolean w)
SDG.Assets.n (System.String Q, Boolean w)
SDG.Assets.n (System.String E)
SDG.Assets+<init>c__Iterator0.MoveNext ()

what does this mean?

**Comment by fr34kyn01535** [comment]
When does it happen?

**Comment by LazyPiggyHD** [comment]
when i start up the server i thing its a mod but i cant find it. idk if this can help though
