### ISSUE TITLE
Infinite load in server Again

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [RocketFoundation/Rocket#139]
In version 4.10.5.0 and 4.10.5.1 I don't,no one else can go again this picture is loading as it should and was deleting the folder Level or Players doesn't help =_=

**Comment by JohnnyChimpo420** [comment]
I am right there with you, might be an unturned bug though

**Comment by ZSHADOWWOLF** [comment]
I have all the latest updates to worked! It's something you have my problem you haven't solved!
