### ISSUE TITLE
Rework RCON to have multiple backend formats(xml/json)

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketFoundation/Rocket#14]
Implement basic I/O and a make output machine readable

**Comment by Hammereditor** [comment]
I agree; I'm having a hard time writing a program to automatically connect to the Telnet RCON server, log in, and send commands. I'd like an XML back-end.

**Comment by fr34kyn01535** [comment]
Well, as this is a feature probably dedicated to hosters, as of right now there is no priority for that.
