### ISSUE TITLE
server colors not working

### ISSUE THREAD

**Issue by sharkbound** [RocketFoundation/Rocket#140]
On my server before i updated to unturned 3.10.6.0 and the rocket version for it i had working chat colors (using color.colorcodehere permission) but after install the newest rocket version (the one for 3.10.6.0) the colors stopped working, its just using defualt gold player and normal white player chat colors :(

**Comment by cartman-2000** [comment]
It was removed.
https://ci.rocket.foundation/job/Rocket%20Beta/375/changes

**Comment by fr34kyn01535** [comment]
It conflicted with Nelsons promise for GOLD buyer that their chat is gold...
