### ISSUE TITLE
Group color on chat messages.

### ISSUE THREAD

**Issue by cartman-2000** [RocketFoundation/Rocket#143]
This could be put down as a potential feature.

I know that it has been removed for now and that nelson doesn't want the gold members chat colors set to something else. 

But what I'm thinking is; would it be possible for a compromise to be made where for instance you could have group colors on groups other than the group that has been set to the default in the rocket config files, and the default group would have normal chat colors? This would take care of most of nelsons problems with it recoloring the gold members chat, as only those that have special group accesses on a server could have a custom chat color.

**Comment by fr34kyn01535** [comment]
Nelson and I will figure something out
