### ISSUE TITLE
Steam.kick not working correctly, stuck on loading screen

### ISSUE THREAD

**Issue by timoguentner** [RocketFoundation/Rocket#144]
I'm currently using Steam.kick in one of my plugins:

Steam.kick(player.CSteamID, "");

But instead of going back to the start screen the kicked player stays stuck in the loading screen.

**Comment by fr34kyn01535** [comment]
I was not able to replicate, where are you kicking the player?

**Comment by timoguentner** [comment]
In my main function Load() I have set a new event:

RocketServerEvents.OnPlayerConnected += Events_OnPlayerConnected;

and in the function of the event I have an if statement where I download a string and check whether its true or false, if its false I kick the player.

**Comment by Zamirathe** [comment]
This happens with Global Ban too.  If you ban someone for say 10 minutes, when they try to reconnect they just sit on the loading screen.  The server kicks them off, as they connect then get kicked, but their client is stuck.

**Comment by fr34kyn01535** [comment]
Yes, kicking in OnPlayerConnected does not really work well. The reason is that clients get the packet that they are logged in, and then get forcefully disconnected - while the client is still connecting.

**Comment by fr34kyn01535** [comment]
@SDGNelson could you add a ref parameter to Steam.ServerConnected that allows us to deny the connection? That would be usefull for custom white or banlists

**Comment by SDGNelson** [comment]
Ok, remind me tonight.

**Comment by DevLeeo** [comment]
that happened with me, i have added 500ms before kick and worked well.

i hope that is corrected.

**Comment by fr34kyn01535** [comment]
Kick in player connected works well now
