### ISSUE TITLE
Lag bug part 2

### ISSUE THREAD

**Issue by h4ugen** [RocketFoundation/Rocket#145]
About a month ago i opened an issue here about a lagbug.

Where everyone in the server would have the exact same ping, and very high.
such as 324 or 285

That bug stopped occurring about a week after I opened the issue
but now, it is back. Last issue was labeled as Unturned bug/wont fix

But now, as I have added rocket back to my server it has started occurring again.

To further explain the issue;

Some time after launching the server, anywhere from 10 minutes to 10 hours
the server suddenly show the same ping for everyone, and everyone lags.
the ping seems to be random between 150 - 500. The lag affects everything in the
server, chat, zombies, guns etc...

**Comment by h4ugen** [comment]
Oh, even typing in the console takes forever.
It can take 10 seconds to get on character in the textfield.

k(10 seconds later)i(10 seconds later)c(10 seconds later)k(10 seconds later)/.....

**Comment by cartman-2000** [comment]
I've generally haven't had that much of a problem with lag on my server's over the past few recent patches unless the server is completely full at 32 players, then it can sometimes go down to a 5-10TPS speed in the lag command, but not that often. Some other things that could also have an effect on the amount of "lag" that you get on the server is the usage of the vanish command(which is a computationally heavy command.), or having a lot of plugins with timers in them as those timers run each frame.

**Comment by fr34kyn01535** [comment]
What are your server specs? (CPU Name, HDD, RAM)

**Comment by cartman-2000** [comment]
For mine it is an Intel i7 2600k(stock clocks.), 128GB SSD drive, and 8GB of ddr3 1600 ram.

**Comment by fr34kyn01535** [comment]
Whats your network specs?

**Comment by h4ugen** [comment]
Sorry for late reply

Intel Xeon E3 1245v2
2 x 2 TB SATA	
32GB ram
Windows 2008 server

**Comment by fr34kyn01535** [comment]
There is no Lag bug. You could have individual problems with your servers, you both seem to not use a dedicated machine - it could be simple as having a bad internet connection.
