### ISSUE TITLE
WorkShop items broken? 

### ISSUE THREAD

**Issue by mryan04290** [RocketFoundation/Rocket#146]
whenever I try to boot up my servers it gives me this (http://prntscr.com/7bchej) but when i take my workshop item out of the content folder it boots up normally? kind of confused lol thanks for the help

-mryan29

**Comment by fr34kyn01535** [comment]
Is that with all workshop items? - What specific item is it? - Does this also happen with Vanilla?

**Comment by mryan04290** [comment]
I think it happens with vanilla and so far its been all workshop items for me which are mostly gun mods and 3 or 4 maps.
