### ISSUE TITLE
Error and lag due to fishing

### ISSUE THREAD

**Issue by mryan04290** [RocketFoundation/Rocket#148]
whenever a player casts a rod in any of my servers i get a huge lag spike and this error (http://prntscr.com/7bnazb) but it doesn't seen to effect the game play of the fishing only the server its self with the error.

**Comment by mryan04290** [comment]
It actually might be linked with someone joining and leaving I'm not sure

**Comment by Zamirathe** [comment]
There was an update with the way Rocket handles events which is where this error comes from.  It will be worked on.

**Comment by mryan04290** [comment]
thanks zami!
