### ISSUE TITLE
(Probably an unturned bug and not rocket) Fishing problem

### ISSUE THREAD

**Issue by JohnnyChimpo420** [RocketFoundation/Rocket#152]
I know this bug is probably something with unturned and not rocket, but i feel like nelson will be more likely to see it here than anywhere else, this happens in the server console

![image](https://cloud.githubusercontent.com/assets/12197966/7905370/727aa904-07e5-11e5-8320-e73ed964336e.png)

**Comment by JohnnyChimpo420** [comment]
Sorry, just noticed that this was open in #148

**Comment by fr34kyn01535** [comment]
Are there any plugins installed, if yes, please remove them all. Can you confirm that this bug appears in Vanilla?

**Comment by JohnnyChimpo420** [comment]
I have tons of pugins installed, I will do a test for vanilla when i have time, I have had a busy few days, I apologize.

**Comment by JohnnyChimpo420** [comment]
Tested on vanilla, no error, then re installed Rocket, and tested again, no error. Seems to have fixed itself, this can probably be removed now.
