### ISSUE TITLE
NullReferenceException in  SDG.BarricadeManager.askToggleDoor

### ISSUE THREAD

**Issue by lightphoenix2** [RocketFoundation/Rocket#154]
[6/1/2015 4:56:01 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.BarricadeManager.askToggleDoor (CSteamID t, Byte w, Byte h, UInt16 t, UInt16 T)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.SteamChannel.receive (CSteamID F, System.Byte[] H, Int32 T, Int32 p)
SDG.Steam.j (CSteamID P, System.Byte[] T, Int32 a, Int32 m, Int32 V)
SDG.Steam.Q (Int32 V)
SDG.Steam.F ()
SDG.Steam.Update ()

[6/1/2015 4:56:02 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.BarricadeManager.askToggleDoor (CSteamID t, Byte w, Byte h, UInt16 t, UInt16 T)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.SteamChannel.receive (CSteamID F, System.Byte[] H, Int32 T, Int32 p)
SDG.Steam.j (CSteamID P, System.Byte[] T, Int32 a, Int32 m, Int32 V)
SDG.Steam.Q (Int32 V)
SDG.Steam.F ()
SDG.Steam.Update ()

[6/1/2015 4:56:02 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.BarricadeManager.askToggleDoor (CSteamID t, Byte w, Byte h, UInt16 t, UInt16 T)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.SteamChannel.receive (CSteamID F, System.Byte[] H, Int32 T, Int32 p)
SDG.Steam.j (CSteamID P, System.Byte[] T, Int32 a, Int32 m, Int32 V)
SDG.Steam.Q (Int32 V)
SDG.Steam.F ()
SDG.Steam.Update ()

**Comment by sharkbound** [comment]
When this happens i just delete barricades.dat from the servers level folder and it fixes it

**Comment by sharkbound** [comment]
Basically there is a glitched door or garage door placed in the map, the only fix i know is to delete all the placed door, crates, gates, torches and so on on the map, also deleting barricades.dat wont delete placed stuctures

**Comment by Zamirathe** [comment]
No, deleting structures.dat will delete the structures.

**Comment by fr34kyn01535** [comment]
Please, be more descriptive in the title...

**Comment by fr34kyn01535** [comment]
Can you replicate this bug in Vanilla?

**Comment by lightphoenix2** [comment]
Hmmmm, but the barricades.dat contain the storage and lockers with all the item inside of them.
