### ISSUE TITLE
Events being retriggered if more than one plugin uses it.

### ISSUE THREAD

**Issue by LeeIzaZombie** [RocketFoundation/Rocket#155]
Hi,

I found this problem while sitting on my IRC channel and I noticed that all the join/leave messages were being sent twice. I looked into it further and noticed the same on my other server, so here's what I have:

![2015-06-01_00001](https://cloud.githubusercontent.com/assets/7387999/7913425/d1c33ade-0867-11e5-997b-77555b11cb27.JPG)

This image shows that I'm using 3 plugins with the same Event running for different reasons.
When the following code runs:

Declaring the Event: 
```
Rocket.Unturned.Events.RocketPlayerEvents.OnPlayerDeath += RocketPlayerEvents_OnPlayerDeath;
```
Running the event: 
```
private void RocketPlayerEvents_OnPlayerDeath(Rocket.Unturned.Player.RocketPlayer player, EDeathCause cause, ELimb limb, Steamworks.CSteamID murderer)
        {
           if (cause.ToString() != "SUICIDE")
          //Skipping a lot of useless code
           RocketChat.Say(Rocket.Unturned.Player.RocketPlayer.FromCSteamID(murderer), this.Configuration.NormalKillENG + " " + player.CharacterName + ". +" + this.Configuration.NormalKill_LP_Gain + " LP", Color.yellow);
        }
```
So when I kill someone, this is the output: 

![2015-06-01_00002](https://cloud.githubusercontent.com/assets/7387999/7913434/ddfc09ac-0867-11e5-908f-bbc2fb0332b7.jpg)

This was not a problem before the latest Rocket Beta versions updated yesterday.

**Comment by LeeIzaZombie** [comment]
With my IRC plugin, the server sends the join message twice because I have another plugin dealing with telling the server what rank of the person is when they join.

**Comment by fr34kyn01535** [comment]
Yep, indeed a bug, fixed in beta408
