### ISSUE TITLE
Not sure if it is rocket or the base game or what - Storage Bug

### ISSUE THREAD

**Issue by BillboardEric** [RocketFoundation/Rocket#156]
Here is a video of the bug
https://www.youtube.com/watch?v=VsuhF8HiUUs
Note: I have modified the storage values of lockers so not sure if that has anything to do with it
If there are any questions, feel free to ask.

**Comment by fr34kyn01535** [comment]
Shutdown does not trigger save, do /save and then /shutdown

**Comment by BillboardEric** [comment]
Even if I leave the area, not only on server shutdown.
