### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#157]
NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie U, Vector3 V, Single U, Single q, SDG.EPlayerKill& h)
SDG.DamageTool.explode (Vector3 X, Single D, EDeathCause N, Single P, Single U, Single d, Single m,
Single G, Single W)
SDG.Grenade.Explode ()

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie U, Vector3 V, Single U, Single q, SDG.EPlayerKill& h)
SDG.DamageTool.explode (Vector3 X, Single D, EDeathCause N, Single P, Single U, Single d, Single m,
Single G, Single W)
SDG.Grenade.Explode ()

**Comment by manuelbarbosa** [comment]
Only one plugin and is not related to zombies / damage or anything like that ...

**Comment by fr34kyn01535** [comment]
Please, descriptive reports

**Comment by fr34kyn01535** [comment]
The cause is explaned in #162

> This happens when you destroy a car with knife (not always) the car explodes and flies to the air > with the scrap metal and falls very slowly.
