### ISSUE TITLE
[Feature] SDG.LightingManager

### ISSUE THREAD

**Issue by LeeIzaZombie** [RocketFoundation/Rocket#158]
Hello,

Would it be possible to implement SDG.LightingManager.Time and SDG.LightingManager.Cycle into Rocket API?

I have a system on a plugin to check the time 0 - 3600 (uint) and the server has it's days and each day I set an event, but the problem is that SDG.LightingManager has obfuscated code and sometimes I can get the right variable like SDG.LightingManager.c but each update it changes and sometimes I change cycle instead of time.

I hope you consider this, thanks for reading.
Kind regards - LeeIzaZombie.

**Comment by falsechicken** [comment]
:+1: Unless there is another solution.

**Comment by fr34kyn01535** [comment]
NEVER use obfascuated methods. Request each unlock with an issue please (Mentioning the class, type, temp name and a proposed new name & explain what it does)
