### ISSUE TITLE
Console is just displaying ASCII chars (No Umlaute, Cyrillic,..)

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketFoundation/Rocket#160]
Nelson has to fix this by changing the Encoding in the StreamWriter to UTF-8

SDG.ConsoleOutput in the constructor, Line 32 

        StreamWriter streamWriter = new StreamWriter(fileStream, Encoding.ASCII)

to

        StreamWriter streamWriter = new StreamWriter(fileStream, Encoding.UTF8)

**Comment by Mashrien** [comment]
:+1:

**Comment by DevLeeo** [comment]
:+1:

**Comment by typicalcoder** [comment]
How can I fix it on my own server?
