### ISSUE TITLE
Unturned player desconnecting

### ISSUE THREAD

**Issue by MyNickIsBetter** [RocketFoundation/Rocket#161]
Recently with these new updates my Rocket started to '' kick '' half of the players on my server. On the server vanilla it does not. I'm sure that updated the Rocket correctly!

My internet is broadband!

I limit my server to 8 players in order to not require much of the capacity of my internet!
My TPS, according to the Rocket plugin is always 0

Thanks!

**Comment by Zamirathe** [comment]
Are you using protected slots?

**Comment by falsechicken** [comment]
Usually that happens when you computer cannot keep up. You are sure its only when you have Rocket?

**Comment by MyNickIsBetter** [comment]
Zamirathe what that's? How to disable these ''protected slots''? How to find out if I am using it?
---------------------

falsechicken my computer have very good processing speed!

**Comment by MyNickIsBetter** [comment]
Zamirathe what that's? How to disable these ''protected slots''? How to find out if I am using it?

falsechicken my computer have very good processing speed!

**Comment by cartman-2000** [comment]
This can happen for several reasons, one is what falsechicken said, that your cpu is too slow and it can't keep up with all the players on the server. The other is if the server is freezing for extended periods of time, which can cause people to go over the set timeout value on the server causing them to DC from the server.

The freezing disconnect can potentially happen if you are using a plugin that uses a Mysql DB, but the DB that you are using isn't a local DB(on the same computer.), but one over a network(much worse if it is a over the internet DB.).

It can help somewhat if you increase the timeout value on the Timeout command(which is in miliseconds.) and put that command in the server's commands.dat file.

**Comment by MyNickIsBetter** [comment]
I not use plugins!

**Comment by cartman-2000** [comment]
Also the TPS value on the server should never show up as "0", the lowest that I have ever seen it get to is 3 TPS and not lower. For example, one of my server's at the moment with 15 players is showing a TPS of 403.

**Comment by MyNickIsBetter** [comment]
cartman-2000 How to increase my TPS?

**Comment by cartman-2000** [comment]
There aren't very many ways to "really" increase the TPS on a server, it is tied to the speed of the core on the cpu. The best you can do, most of the time, is to reduce the amount of other stuff running on the system that the server is running on. However, if it is really showing a TPS of 0 on your server, than something else might be wrong with it, or rocket, since that isn't supposed to happen.

**Comment by MyNickIsBetter** [comment]
Then the timeout command does not work, how can you help me? What great value to put in timeout?

**Comment by cartman-2000** [comment]
You can try the value 5000 for a 5 second timeout.

**Comment by MyNickIsBetter** [comment]
cartman-2000 thank you! But if that does not work? What I can try to increase the TPS my server or him to stop ''kick'' half of the players from my server?

**Comment by fr34kyn01535** [comment]
If your TPS is at 0 that means you get better hardware.Something is keeping your server in trouble, maybe to many items on the map, maybe autosave interval of 0, It means your server "processes" less then a frame per second,.. Pretty simple.

**Comment by MyNickIsBetter** [comment]
Thank you!
