### ISSUE TITLE
Exception, and I know why.

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#162]
#### When this happens, the console throws this exception:

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie J, Vector3 J, Single j, Single O, SDG.EPlayerKill& H)
SDG.DamageTool.explode (Vector3 K, Single j, EDeathCause w, Single Q, Single g, Single h, Single P,
Single Y, Single i)
SDG.InteractableVehicle.FixedUpdate ()

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie J, Vector3 J, Single j, Single O, SDG.EPlayerKill& H)
SDG.DamageTool.explode (Vector3 K, Single j, EDeathCause w, Single Q, Single g, Single h, Single P,
Single Y, Single i)
SDG.InteractableVehicle.FixedUpdate ()

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie J, Vector3 J, Single j, Single O, SDG.EPlayerKill& H)
SDG.DamageTool.explode (Vector3 K, Single j, EDeathCause w, Single Q, Single g, Single h, Single P,
Single Y, Single i)
SDG.InteractableVehicle.FixedUpdate ()

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie J, Vector3 J, Single j, Single O, SDG.EPlayerKill& H)
SDG.DamageTool.explode (Vector3 K, Single j, EDeathCause w, Single Q, Single g, Single h, Single P,
Single Y, Single i)
SDG.InteractableVehicle.FixedUpdate ()

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie J, Vector3 J, Single j, Single O, SDG.EPlayerKill& H)
SDG.DamageTool.explode (Vector3 K, Single j, EDeathCause w, Single Q, Single g, Single h, Single P,
Single Y, Single i)
SDG.InteractableVehicle.FixedUpdate ()

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie J, Vector3 J, Single j, Single O, SDG.EPlayerKill& H)
SDG.DamageTool.explode (Vector3 K, Single j, EDeathCause w, Single Q, Single g, Single h, Single P,
Single Y, Single i)
SDG.InteractableVehicle.FixedUpdate ()

NullReferenceException: Object reference not set to an instance of an object - SDG.DamageTool.damage
 (SDG.Zombie J, Vector3 J, Single j, Single O, SDG.EPlayerKill& H)
SDG.DamageTool.explode (Vector3 K, Single j, EDeathCause w, Single Q, Single g, Single h, Single P,
Single Y, Single i)
SDG.InteractableVehicle.FixedUpdate ()

**Comment by fr34kyn01535** [comment]
Not descriptive... Please -.-

**Comment by fr34kyn01535** [comment]
Btw this is a duplicate to #157
