### ISSUE TITLE
Storage Bug

### ISSUE THREAD

**Issue by BillboardEric** [RocketFoundation/Rocket#163]
My other topic was closed with an answer that didn't solve the issue as I did not explain it well enough.
When some sort of storage unit (locker / crate) is placed (seems apparent around a large quantity of structures) it will stay there and stuff can be put in. When the area is unloaded (when a player is not nearby) the locker / crate disappears. When placing the same type of storage in its previous place (ie a locker where a locker was) it appears and still contains the items deposited, but disappears once again when the area is unloaded.

**Comment by AHappyTeddyBear** [comment]
There is a simple and easy fix that you can do yourself to solve the disappearing crates or lockers considering it is a player side implementation therefore a glitch that is not server side. Simple navigate into "steamapps" > "common" > "Unturned" > Then search for the folder "Structures" and the folder "Barricades" by using the search command. (Make sure you are searching in the "Unturned" folder). Proceed to delete the "Structures" and "Barricades" folders. Next, go into the Steam Library, right click on Unturned, select "Properties" in the drop down menu, go under the "Local Files" tab, and click "Verify Integrity of Local Game Cache". This will reinstall the 2 folders you deleted and when you log back into a server the missing crates will reappear with the loot in them. Your welcome :)

**Comment by BillboardEric** [comment]
Thanks @AHappyTeddyBear, but other players also don't see the crates / lockers so it is not just on my side. Also, I am testing to see if the bug involves me modifying the values of crate and locker size server side because I think that may be the issue. I'll report back when I find out.

**Comment by fr34kyn01535** [comment]
Very simple quesion, is this bug replicable on a untouched FRESH install both on the server & client?

**Comment by cartman-2000** [comment]
This bug is related to this bug. As I've had this happen like this on my server before and it fixed after I started to drain the items out of the glitched container.
https://github.com/SmartlyDressedGames/Unturned/issues/4

**Comment by cartman-2000** [comment]
This should have been fixed as of the v3.11.1.0 update of unturned.
