### ISSUE TITLE
Weapons/Mags

### ISSUE THREAD

**Issue by crook47** [RocketFoundation/Rocket#165]
After dieing, i come back to my body to re loot my items and i have to disconnect then reconnect to be able to reload my mags, and/or add ammo from boxes to my mags.

**Comment by falsechicken** [comment]
Is this a Rocket issue? Have you tested it without Rocket?

**Comment by crook47** [comment]
I just recently started using rocket on my server. Before that completely vanilla and I never had to disconnect to reload. Something like that is rather memorable as it's quite annoying.

**Comment by fr34kyn01535** [comment]
Any errors in the console? Please try it in vanilla with the CURRENT version..

**Comment by crook47** [comment]
No errors on the console. Im just gonna go ahead and close this issue. I made it pretty clear in my last message that this is not an issue with a vanilla server. I must not come across as competent enough for you to believe me so if you find this is an error with rocket please don't re open this.

**Comment by falsechicken** [comment]
So to recap: There are no console errors an no one else is commenting on this issue mentioning that it is affecting them. What would you expect anyone to do about it? There was nothing to go on to begin with.
