### ISSUE TITLE
/z is not working.

### ISSUE THREAD

**Issue by ssitowitz** [RocketFoundation/Rocket#168]
Whenever I use /z it says it spawns zombies but none are spawned.

**Comment by Zamirathe** [comment]
Confirmed with another admin.  Will be looked into.

**Comment by fr34kyn01535** [comment]
Not my fault :D

![](https://screenshots.bam.yt/7466b7f9158a7c03ddb085d7b242b804.png)

**Comment by fr34kyn01535** [comment]
Removed /z from Rocket.
