### ISSUE TITLE
admin (steam id) and unadmin (steam id), invalid parameter (i think is a bug)

### ISSUE THREAD

**Issue by sharkbound** [RocketFoundation/Rocket#171]
i was trying to unadmin somebody using unadmin steam64idhere, and it said invalid parameter, it will only let me admin or unadmin somebody if they are connected to the server, tried unadmin "steam64id" and it still said it, and i did use the command from console, i know it cant be used from in-game anymore..

and also there isnt any messages from console when u do it with someone connected ether

**Comment by JohnnyChimpo420** [comment]
/duty is also not working,i cannot unadmin at all

**Comment by JohnnyChimpo420** [comment]
Just checked vanilla, and unadmin worked, so it must be a rocket bug

**Comment by sharkbound** [comment]
/duty was remove in a recent rocket build just to let u know

**Comment by Zamirathe** [comment]
This was set with Rocket to be only available in the console, not in game.

**Comment by JohnnyChimpo420** [comment]
I tried doing unadmin in the console and all it said was "Invalid parameter", but it isn't a problem for me really since I am the only admin anyway :)

**Comment by JohnnyChimpo420** [comment]
I stand corrected, it is working.

**Comment by sharkbound** [comment]
Well if the player your trying to admin/unadmin is connected to the server it does it it just doesnt say it didit, but if utry to admin/unadmin a player using their steamid64 it says invalid parsmeters

**Comment by sharkbound** [comment]
And i had no issues with admining/unadmining players using steam64id before this version of rocket

**Comment by fr34kyn01535** [comment]
The admin/unadmin commands are now part of Rocket, those didn't parse the id in the past. Added this functionality now.
