### ISSUE TITLE
3 tps with full server on powerful pc.

### ISSUE THREAD

**Issue by Alvetore** [RocketFoundation/Rocket#172]
When my server is full, /lag writes me only 3 TPS. And all players have ping 500+
Six-Core processor 2.6 Ghz, 4 gb ram and 1 gigabit internet... 20 slots.
There was no such problem earlier... 
There is forum topic with same problem: https://rocket.foundation/viewtopic.php?f=3&t=382

**Comment by falsechicken** [comment]
Is this a Rocket or Vanilla issue? Please test it without Rocket.

**Comment by Alvetore** [comment]
I think that is Rocket issue. There is no problem on the older version of Rocket. Turned on testing server without Rocket.
