### ISSUE TITLE
RocketPlayer.Ban does not work

### ISSUE THREAD

**Issue by Kirollos** [RocketFoundation/Rocket#173]
Hi there,

Apparently using RocketPlayer.Ban does not ban the player, it just kicks them telling the reason & duration, but the ban is not set.

This is a part of my code.

```csharp
string pname = msg.Split(' ')[0];
string durationstr = msg.Split(' ')[1];
int duration = 0;
if(!int.TryParse(durationstr, out duration))
{
	this.Send("PRIVMSG " + this._channel + " :[ERROR] duration \""+durationstr+"\" is not valid.");
	return;
}
string reason = msg.Remove(0, pname.Length + durationstr.Length + 1 + 1);
RocketPlayer pPointer = RocketPlayer.FromName(pname);
if (pPointer == null)
	this.Send("PRIVMSG " + this._channel + " :[ERROR] Player " + pname + " not found.");
else
{
	pPointer.Ban(reason, (uint) duration);
	this.Send("PRIVMSG " + this._channel + " :[SUCCESS] Player " + pname + " is banned!");
}
```

Note: pname is a valid nick, because it actually kicks the player with no problem, but the ban itself is not set.

I'm not really sure if it's a bug or an issue on my side. I'm using Rocket Unturned v4.4.1.0

Thanks.

**Comment by fr34kyn01535** [comment]
Ban is not part of Rocket

**Comment by manuelbarbosa** [comment]
Then why does RocketPlayer have a Ban method :P remove silly code from your class

**Comment by Zamirathe** [comment]
It is a easy way to reference Unturned's ban without having to call into SDG for that function.  Just like many of the other features on RocketPlayer.

**Comment by fr34kyn01535** [comment]
What i wanted to say is, we are calling nelsons method directly, if that doesn't ban there is something else wrong. Without any exception i am not willing to look into this tho as i cant replicate..

**Comment by manuelbarbosa** [comment]
@Kirollos have you tested using SDG Ban directly?

**Comment by fr34kyn01535** [comment]
That makes no difference, RocketPlayer.Ban is literally just a redirect to SDG.Ban
