### ISSUE TITLE
Rocket not loading plugins when launched by .bat

### ISSUE THREAD

**Issue by JzJad** [RocketFoundation/Rocket#174]
When I launch my server with my keep alive script, it does not load plugins, and for some reasons loads the default rocket config. Any one know why?

**Script**
```batch
@echo Server status monitor running...
@echo off
:loop
tasklist /nh /fi "imagename eq Unturned.exe" | find /i "Unturned.exe" > nul || "C:\Program Files (x86)\Steam\steamapps\common\Unturned\Unturned.exe" -nographics -batchmode +secureserver/TheUnknown
goto loop
```

**Comment by JzJad** [comment]
Found a quick round about way, I set my script to launch the Server.lnk that I was previously using, and it loaded the plugins... weird.

**Comment by fr34kyn01535** [comment]
Make sure to switch to the workdirectory
