### ISSUE TITLE
Latest beta [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.AnimalManager.FixedUpdate ()

### ISSUE THREAD

**Issue by McDrakon123** [RocketFoundation/Rocket#176]
When i load up my server with the latest beta i just get this message spammed in the console.

>[Error] NullReferenceException: Object reference not set to an instance of an object - SDG.AnimalManager.FixedUpdate ()

**Comment by JohnnyChimpo420** [comment]
If you have steamcmd try running it to update your second installation, it helped me

**Comment by fr34kyn01535** [comment]
https://github.com/RocketFoundation/Rocket/wiki/Fixing-Issues
