### ISSUE TITLE
Player death messages in chat

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketFoundation/Rocket#177]

**Comment by NNickey** [comment]
This feature is already available as a plugin. Don't request it if it can be made as a plugin.
https://dev.rocket.foundation/plugins/death-messages/

**Comment by fr34kyn01535** [comment]
Well since its very basic i wanted to have it in Rocket ;D

**Comment by manuelbarbosa** [comment]
I agree with NNickey! whyy??
