### ISSUE TITLE
Generated items not interectable

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#179]
Generated items using ``` ItemManager.dropItem(); ``` can not be picked up for some reason.

**Comment by fr34kyn01535** [comment]
Examples pls, have you tried it yourself?

**Comment by manuelbarbosa** [comment]
Yes, Generate a item using ItemManager.dropItem() and try to pick it up

**Comment by manuelbarbosa** [comment]
@SDGNelson  could you explain the parameters for ItemManager.dropItem(Item C, Vector3 e, bool c, bool w, bool j); please? (the last 3 bools)

**Comment by manuelbarbosa** [comment]
After a loooooottttt of testing, I discovered it is because of the height that they are falling.
Any item falling from (ground.y + 15) cannot be picked up.

ItemManager.dropItem(new Item(300, true), new Vector3(location.x, location.y + 50, location.z), true, true, true);

This can't be picked up despite durability at 100 (location is player.location)
