### ISSUE TITLE
Reserved slots

### ISSUE THREAD

**Issue by bernas293** [RocketFoundation/Rocket#183]
Hi guys, im being notice that happens in my server, i have a 5 reserved slots to some players, and my server supportrs 20 slots. So it should have 15players + 5 vips playing. but this doens happen... i have for example 15/20 players playing including in this 15, some of the vip players, and people can join because of the 15 reserved slots.

**Comment by manuelbarbosa** [comment]
I confirm this on my server as well, got down from 18 to 16 because of 2 reserved since last update

**Comment by fr34kyn01535** [comment]
Not a bug, intended functionality
