### ISSUE TITLE
Generator Refuel

### ISSUE THREAD

**Issue by crook47** [RocketFoundation/Rocket#185]
Generators cannot be refueled, tried on a non rocket server, fuels up, rocket server wont take fuel.

**Comment by crook47** [comment]
So if i fill the generatorss a few times, disconnect and reconnect it will show 100%

**Comment by crook47** [comment]
Once agian i give you another issue with rocket and you just throw it under the bus, i guess ill juts stop giving you bugs then lol

**Comment by fr34kyn01535** [comment]
I tried to replicate it and couldnt. I am happy you sorted it out yourself.
