### ISSUE TITLE
Rocket file I/O fails complety on Linux / Mono

### ISSUE THREAD

**Issue by Trojaner25** [RocketFoundation/Rocket#186]
It doesnt even create the Rocket folder at < Unturned>/Servers/< Serverinstance>/.
I created the directory manually and moved some plugins to < Unturned>/Servers/< Serverinstance>/Rocket/Plugins. They are for the latest Rocket  version (4.4.1.0) which is the one I am using, but none of them work nor they appear in the log file (the Player.log, not the Rocket log since it doesn't get created). The config file for permissions etc are also missing and were not created.

Well, I can still use the build-in commands of Rocket (e.g. /god) and the logs show that Rocket has been successfully loaded. I didn't found any exceptions of it.

(Unturned has been installed with Steamcmd and launched with mono)

Tested it successfully on Windows with the same setup.

**Comment by fr34kyn01535** [comment]
Are you using the Linux build? I can't replicate, loading plugins works for me on linux

**Comment by Trojaner25** [comment]
I downloaded the latest version from "Get Rocket"

**Comment by fr34kyn01535** [comment]
Why do you think that this version works with linux? Why do you consider this a bug?

**Comment by fr34kyn01535** [comment]
See https://rocket.foundation/api for more information on the linux builds

**Comment by Trojaner25** [comment]
It never said anywhere that there is a version for linux. I though that was a universal version which could be used on both - Linux and Windows

**Comment by fr34kyn01535** [comment]
The windows build of Unturned 3 does also not work on linux, why should the windows build of Rocket do :P
