### ISSUE TITLE
RocketChat Handler

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#188]
Please add a public RocketChat.Say Event so it's possible to broadcast the messages that pass through RocketChat for example for the IRC plugins.

**Comment by Trojaner25** [comment]
+1

**Comment by fr34kyn01535** [comment]
public delegate void PlayerChatted(RocketPlayer player, ref Color color, string message);
public static event PlayerChatted OnPlayerChatted;

Is in RocketPlayer for a few weeks now

**Comment by manuelbarbosa** [comment]
That we already know it exists, we want for EVERYTHING.
IRC Plugin already uses that event, we want the all package :) console messages without a player that pass through RocketChat also.

**Comment by fr34kyn01535** [comment]
Since i haven't implemented async events yet, implementing an event OnLog would not be very wise
