### ISSUE TITLE
Can't log on to the server Unturned

### ISSUE THREAD

**Issue by CharlesGame** [RocketFoundation/Rocket#190]
![2015-06-21_00001](https://cloud.githubusercontent.com/assets/12815714/8272130/9aad6542-1848-11e5-8158-f512fd8a5da4.jpg)
Can't connect the server generates an error.Can explain the reason?

**Comment by DronXa** [comment]
Freaky this is a Unturned Bug #Bug

**Comment by Zamirathe** [comment]
It means the server isn't running the same version of Unturned as you are.

**Comment by fr34kyn01535** [comment]
Its not a bug, delete your Unturned folder & reinstall
