### ISSUE TITLE
Crash with startup

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [RocketFoundation/Rocket#191]
This problem started with the update 3.11.00 game crashes with the message "stopped working" I reinstalled,I checked the cache,I deleted the mods,I did the most simple ways..but it doesn't help I'm turning here for help because my server also suffered from this and gives the same error

**Comment by cartman-2000** [comment]
Are you running on 32 bit windows? The update added support for 64 bit windows, but it has caused problems for those that have 32 bit windows, with either the game crashing on start or the modified files error when you go to connect to a server.

**Comment by ZSHADOWWOLF** [comment]
No 64x and 86x

**Comment by cartman-2000** [comment]
does the game give any crash/error info in the game's debug log, for either the server or client?

**Comment by ZSHADOWWOLF** [comment]
Where lies the path of the log of the client?

**Comment by ZSHADOWWOLF** [comment]
Here is log in error Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	Unturned.exe
  Версия приложения:	5.1.0.28848
  Отметка времени приложения:	556c86c4
  Имя модуля с ошибкой:	Unturned.exe
  Версия модуля с ошибкой:	5.1.0.28848
  Отметка времени модуля с ошибкой:	556c86c4
  Код исключения:	c000001d
  Смещение исключения:	00000000002b3037
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	1b73
  Дополнительные сведения 2:	1b730e7e33f3f974833c8e324365646d
  Дополнительные сведения 3:	ef4a
  Дополнительные сведения 4:	ef4aebdc57c83638d6669896931cbe50

**Comment by fr34kyn01535** [comment]
There was no rocket out for this version..

**Comment by ZSHADOWWOLF** [comment]
But I need help! I have not started the game,and thus the server! In the trims I was not given any help!!!

**Comment by fr34kyn01535** [comment]
This is not a support forum for Unturned 3, if you have any issues report them to Nelson (https://github.com/SmartlyDressedGames/Unturned/issues)
