### ISSUE TITLE
The problem with the gun

### ISSUE THREAD

**Issue by CharlesGame** [RocketFoundation/Rocket#193]
The problem with an eye for shadow Stalker.The sight simply red don't
![2015-06-22_00001](https://cloud.githubusercontent.com/assets/12815714/8280670/8f891dd4-18f0-11e5-803c-a63ca01a0427.jpg)
![Uploading 2015-06-22_00002.jpg…]()

**Comment by Zamirathe** [comment]
Please report all Unturned bugs to Nelson.
