### ISSUE TITLE
Plugins won't work.

### ISSUE THREAD

**Issue by markrasher** [RocketFoundation/Rocket#195]
Before the last update everything worked fine. but now when i updated my server, and started it, the console went crazy. ton of errors and when i join the server, all the plugins don't work. 
Here's the console:
![image](https://cloud.githubusercontent.com/assets/8477642/8305275/1de8e364-19b6-11e5-8da5-b3f0a938a101.png)
When i delete the feast plugin the console doesn't go that crazy, but the plugins still don't work. any help?

**Comment by fr34kyn01535** [comment]
This is not a issue regarding Rocket, please see https://rocket.foundation/viewtopic.php?f=44&p=1585#p1585
