### ISSUE TITLE
Not working on linux with 3.11.0.2

### ISSUE THREAD

**Issue by Trojaner25** [RocketFoundation/Rocket#197]
Yes, I'm using the latest linux beta build.

Exception:
```
Begin MonoManager ReloadAssembly
Platform assembly: /home/mcuser/Unturned/Unturned_Data/Managed/UnityEngine.dll (th
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.RocketConsole.DoRead () [0x00000] in <filename unknown>:0
Stacktrace:


Native stacktrace:

        /home/mcuser/Unturned/Unturned_Data/Mono/x86_64/libmono.so(+0x915c6) [0x7f30be1de5c6]
        /home/mcuser/Unturned/Unturned_Data/Mono/x86_64/libmono.so(+0x3481b) [0x7f30be18181b]
        /lib64/libpthread.so.0(+0xf9f0) [0x7f30c18949f0]
        ./Unturned.x86_64() [0xb2aaf5]
        ./Unturned.x86_64() [0x712459]
        ./Unturned.x86_64() [0x45edcf]
        /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f30c011bbe5]
        ./Unturned.x86_64() [0x467ffd]
```

**Comment by fr34kyn01535** [comment]
Is there more to this issue? Additional error logs & informations?

**Comment by Trojaner25** [comment]
At the top of the log:
```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) functioFMOD failed to initialize ... Error initializing output device.

(Filename:  Line: 477)
```

But this also happend on older versions, which were working fine...

When starting the server with the x86 executable, it fails starting steamwork (which should be related to unturned), so I can't test it on x86.

**Comment by fr34kyn01535** [comment]
I haven't tested 64bit server yet, install Steam (and the 32bit dependencies) to make it work with the 32bit version, ALSA is your sound driver, that has nothing to do with our problem..

**Comment by Trojaner25** [comment]
Its a root server with no desktop, so I can't install steam.

However, the x86 versions worked fine with 3.10.8.5, so I guess its an unturned issue.

**Comment by fr34kyn01535** [comment]
Wait, are you able to run vanilla?

**Comment by Trojaner25** [comment]
I will try it

**Comment by Trojaner25** [comment]
Seems like its caused by Unturned (log from 3.11.0.2 without rocket):
```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) functioFMOD failed to initialize ... Error initializing output device.

(Filename:  Line: 477)

Begin MonoManager ReloadAssembly
Platform assembly: /home/mcuser/Unturned/Unturned_Data/Managed/UnityEngine.dll (thStacktrace:


Native stacktrace:

        /home/mcuser/Unturned/Unturned_Data/Mono/x86_64/libmono.so(+0x915c6) [0x7f7b4d89f5c6]
        /home/mcuser/Unturned/Unturned_Data/Mono/x86_64/libmono.so(+0x3481b) [0x7f7b4d84281b]
        /lib64/libpthread.so.0(+0xf9f0) [0x7f7b50f559f0]
        ./Unturned.x86_64() [0xb2aaf5]
        ./Unturned.x86_64() [0x712459]
        ./Unturned.x86_64() [0x45edcf]
        /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f7b4f7dcbe5]
        ./Unturned.x86_64() [0x467ffd]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
```

**Comment by Trojaner25** [comment]
I know this isn't related to rocket anymore, but where can I report unturned specified bugs? Is there a kind of bugtracker or something? Its sad that there is currently no way running a x64 unturned server on linux root servers

**Comment by fr34kyn01535** [comment]
I'll tell Nelson, as i said, there is an issue with cross platform compability right now anyway, maybe yours will end up being fixed the next weeks along with the others..

**Comment by DevPre** [comment]
I've also a SIGSEGV error with 2.6.32-042stab104.1 x86_64

Error code:
root@5conp5vj:~/steamcmd# cd unt
root@5conp5vj:~/steamcmd/unt# ./Unturned.x86_64 -nographics -batchmode +secureserver/testserver
Set current directory to /root/steamcmd/unt
Found path: /root/steamcmd/unt/Unturned.x86_64
Mono path[0] = '/root/steamcmd/unt/Unturned_Data/Managed'
Mono path[1] = '/root/steamcmd/unt/Unturned_Data/Mono'
Mono config path = '/root/steamcmd/unt/Unturned_Data/Mono/etc'
displaymanager : trying .X11-unix
Stacktrace:


Native stacktrace:

        /root/steamcmd/unt/Unturned_Data/Mono/x86_64/libmono.so(+0x915e6) [0x7f8629ca25e6]
        /root/steamcmd/unt/Unturned_Data/Mono/x86_64/libmono.so(+0x3483b) [0x7f8629c4583b]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0) [0x7f862d346cb0]
        /usr/lib/x86_64-linux-gnu/libX11.so.6(+0x683b8) [0x7f862cc023b8]
        /usr/lib/x86_64-linux-gnu/libX11.so.6(_XimSetICDefaults+0xe1) [0x7f862cc03631]
        /usr/lib/x86_64-linux-gnu/libX11.so.6(_XimSetICDefaults+0x15e) [0x7f862cc036ae]
        /usr/lib/x86_64-linux-gnu/libX11.so.6(_XimLocalCreateIC+0x232) [0x7f862cbff072]
        /usr/lib/x86_64-linux-gnu/libX11.so.6(XCreateIC+0xe3) [0x7f862cbe4a93]
        ./Unturned.x86_64() [0xd6b320]
        ./Unturned.x86_64() [0xd618eb]
        ./Unturned.x86_64() [0x73d7e5]
        ./Unturned.x86_64() [0x7109f1]
        ./Unturned.x86_64() [0x45e664]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f862bbd976d]
        ./Unturned.x86_64() [0x46813d]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted

**Comment by gustav9797** [comment]
I'm also having these issues. Happens quite randomly, maybe when the server starts up or when it has been running for a few hours. 
Rocket build 721. Unturned 3.17.2.0.
`Loading item assets: 933/1158
Loading item assets: 958/1158
Loading item assets: 1008/1158
Loading item assets: 1033/1158
Loading item assets: 1058/1158
Loading item assets: 1083/1158
Loading item assets: 1133/1158
Stacktrace:


Native stacktrace:

        mono() [0x49ff2f]
        mono() [0x4f390e]
        mono() [0x426c19]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x113d0) [0x7f6228c633d0]
        mono() [0x53d992]
        /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so(+0x249d6f) [0x7f622655fd6f]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted (core dumped)
`
