### ISSUE TITLE
Issue with your wordpress site

### ISSUE THREAD

**Issue by Paxination** [RocketFoundation/Rocket#20]
I have been trying to get on your site for a week now and I cant.  I registered and was never sent an email confirmation or a password.  I tried reregistering and it does nothing.  You really need to fix this.

**Comment by fr34kyn01535** [comment]
As you can see on forum & plugin site plenty of other people registered in the same time, try to use an e-mail address from another provider. (What provider do you have?)

**Comment by Paxination** [comment]
My ISP is Charter Communications.  My email is orion_pax@charter.net.  This is a first time ever I have had an issue like this before.  They do not filter spam.  My email software, thunderbird isnt setup to do so, and yes I checked my spam/junk folder just in case.

This isnt on my end.  I am still receiving like 20 emails a day still from the other sites i register on.  Yours being the only one that I am not receiving mail from.  Do you not have an admin panel or something you can check my details in?

**Comment by fr34kyn01535** [comment]
Your e-mail address is correct, when sending to your mailserver i get the following tho:
Mar  1 05:29:22 sm-mta[4327]: t215TLaV004325: t215TMaV004327: DSN: Service unavailable

**Comment by fr34kyn01535** [comment]
Can you try registering again now pls?

**Comment by Paxination** [comment]
Yeah same thing.  It seems it is on my isp's side.  After googling part of that error its possible for some reason your sites IP could be blacklisted on charters side.  Or other things, but that was the most common one i fount.

If you could, could you email me from your personal email and I'll reply with a password of my liking for the site?

**Comment by fr34kyn01535** [comment]
Well i set hostname, hostentry, checked mx records, everything looked fine to me. Your user is activated now.

**Comment by Zamirathe** [comment]
I had the same issue the first time I tried to register Paxination.  What I ended up having to do was re-register with my Gmail account to get the email.  Then you can update your profile to change your nickname to your old username and display only nickname if you'd like to keep the original to display.
