### ISSUE TITLE
Create start script for x64

### ISSUE THREAD

**Issue by Trojaner25** [RocketFoundation/Rocket#201]
Maybe just name it start64.sh and replace Unturned.x86 with Unturned.x86_64

Or try to get the architecture with the script (http://stackoverflow.com/a/246014) and start the correct executable automatically

**Comment by fr34kyn01535** [comment]
Just change the script yourself, i am sure linux users know how to edit a script.

**Comment by Trojaner25** [comment]
I know, but its just a suggestion for other users.

**Comment by fr34kyn01535** [comment]
They shouldnt use linux then ;)

**Comment by Trojaner25** [comment]
Really? Seems like rocket is not very user-friendly...

**Comment by fr34kyn01535** [comment]
Thats not my intention, true, with user friendliness comes support, a service which i can't posibly offer.
