### ISSUE TITLE
Car bug

### ISSUE THREAD

**Issue by BioSpinGaming** [RocketFoundation/Rocket#203]
Ever since I installed Rocket onto my server, when I get in a vehicle and hit 25 speed, it starts vibrating right and left. It then gets back to normal when I get to 60 speed, but some vehicles dont go that fast, what do I do?

**Comment by NNickey** [comment]
This does not sound like a bug, sounds more like the vehicle has been damaged or that the vehicle is big.
It does this for realism?

**Comment by cartman-2000** [comment]
It maybe some of the bugs with the game updating to unity 5, it did cause some problems for the vehicles on the server's(slow vehicles, vehicles glitching out.).

**Comment by fr34kyn01535** [comment]
Does it happen in vanilla Unturned 3? I can't believe i am still asking this...
