### ISSUE TITLE
permissions file blank

### ISSUE THREAD

**Issue by xnlkox** [RocketFoundation/Rocket#204]
I dont know if anyone else has this issue, but I rent a server, and when i access and open the permissions file via FTP it is opening up blank and I am having to keep an updated copy in order to update and change it. Not sure if this is an issue from Rocket or the people I am renting a server from

**Comment by Zamirathe** [comment]
Some files don't like to be opened via FTP.  Make sure you are doing edit otherwise keep a copy on your computer, make your updates on your computer, then upload to the server.

**Comment by fr34kyn01535** [comment]
It's not Rockets fault.
