### ISSUE TITLE
Plugins don't load when using System.Linq

### ISSUE THREAD

**Issue by Trojaner25** [RocketFoundation/Rocket#208]
If you have the "using System.Linq" statement in a plugin (you don't even have to use it, the "using" part is enough), that plugin won't load, no errors in console, its just like the plugin doesn't exists.

**Comment by fr34kyn01535** [comment]
Using it in all my plugins, make sure the project is .NET 3.5

**Comment by cartman-2000** [comment]
I haven't had any trouble on my plugins that use System.Linq, rocket itself also uses Linq for some of the class files.

**Comment by robnauticus** [comment]
I was having this issue myself. Had to re-write all of my Linq queries and
use foreach. I still occasionally un-comment my Linq code to see if it
works, no luck recently...

**Comment by fr34kyn01535** [comment]
Please. Read.
