### ISSUE TITLE
/tp and /tphere teleport location bug

### ISSUE THREAD

**Issue by sharkbound** [RocketFoundation/Rocket#209]
in the current rocket beta build 470 for 3.11.0.5 if u use /tp or /tphere it puts u way under the map in water, when u relog it puts u back on land, but currently it will put u WAY under the map when u use rocket's tp commands

**Comment by Zamirathe** [comment]
Tested it on another server.  Only happened for me while in god mode.  If god mode is disabled, tp works just fine.

**Comment by sharkbound** [comment]
Well thats interesting, the strange things updates can messup never cease to amaze me

**Comment by Zamirathe** [comment]
Are there any errors in your console by chance?

**Comment by sharkbound** [comment]
None that i remember, and i normally keep a close eye on the server console

**Comment by fr34kyn01535** [comment]
I added a feature that does detect god mode and teleports you under the world so it would not flicker, probably messed something up here..

**Comment by fr34kyn01535** [comment]
Reverted the change, weird..
