### ISSUE TITLE
teleport issue

### ISSUE THREAD

**Issue by xnlkox** [RocketFoundation/Rocket#213]
I am running into an issue that when I use the /tp feature, I am being teleported to right area, however I am under the map stuck in water unable to move. I have to exit the server and reconnect  to fix it. please fix this bug =D

**Comment by kaegann** [comment]
its an issue of having god mode enabled while teleporting, they said they fixed it but they talk out their ass a lot here on the bug tracker so who know when or if it will ever be fixed.

**Comment by kaegann** [comment]
I stand corrected, it has been fixed!
