### ISSUE TITLE
Global ban issue

### ISSUE THREAD

**Issue by art1fact** [RocketFoundation/Rocket#216]
So, I still get this error after all of your changes in this plugin:
[Exception] GlobalBan >> Exception in Execute: System.NullReferenceException: Object reference not set to an instance of an object
  at unturned.ROCKS.GlobalBan.CommandBan.Execute (Rocket.Unturned.Player.RocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0

**Comment by Trojaner25** [comment]
Please report this at https://github.com/unturnedROCKS/GlobalBan, this is not an rocket issue

**Comment by art1fact** [comment]
oh, sorry
