### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by pardisproud** [RocketFoundation/Rocket#217]
The server will run for a while and everything will work fine and then all of a sudden it will crash and tell me to send you guys this file. I don't think it's unturned because I've tried reinstalling unturned, rocket and all the plugins. please help. 

http://download1504.mediafire.com/viimkh0hsw7g/ja83azi3tl1ewb9/Rocket+Crash.zip

**Comment by kaegann** [comment]
If it was the crash next to the exe in a folder named with a timestamp that is an unturned crash, not rocket. In which you should be sending it to Nelson.

**Comment by pardisproud** [comment]
ok, thanks and how do i send it to him?

**Comment by kaegann** [comment]
Click the discussions tab on the unturned steam page, then post a new topic in the unturned 3.x bugs section!

**Comment by pardisproud** [comment]
ok thank you very much!

**Comment by Trojaner25** [comment]
You can also report it here: https://github.com/SmartlyDressedGames/Unturned/issues
