### ISSUE TITLE
Additional configuration files

### ISSUE THREAD

**Issue by micktu** [RocketFoundation/Rocket#218]
Currently hard-coded as Plugins/AssemblyName, should be optional (in case we have a bunch of same family plugins, or we want extra configuration serialized at a configurable path).

**Comment by fr34kyn01535** [comment]
Extra configuration files makes sense, i was thinking bout adding this, i would still want to limit the folder to be the same as the assembly name and in the plugins folder.

**Comment by manuelbarbosa** [comment]
:+1:

**Comment by micktu** [comment]
Well, the whole point of the proposal was to get rid of multiple folders all containing a single configuration file.

**Comment by fr34kyn01535** [comment]
Just as they are multiple plugins there are multiple plugins. I don't think people that install plugins with having all translations, configurations, mysqlite dbs or additional configuration files in one folder...

**Comment by Mashrien** [comment]
Have to agree with Sven on that one, having a cluster of configs all dropped into one folder is just a headache. The ASM>Folder arrangement is much cleaner.

**Comment by micktu** [comment]
It's not about Rocket, it's about letting the developer choose a sub-directory of their own, useful in case of modular plug-ins.

**Comment by fr34kyn01535** [comment]
Having different folders for plugin names is not a feature for better customization but would cause confusion. A plugin framework should prevent such things..

**Comment by fr34kyn01535** [comment]
Added.
XMLFileAsset<YourType> = configuration = new XMLFileAsset<YourType>(string.Format(Core.Environment.PluginConfigurationFileTemplate, Name, "mycustomconfig"));
