### ISSUE TITLE
Worst developers ever!

### ISSUE THREAD

**Issue by kaegann2** [RocketFoundation/Rocket#222]
I have never seen a sorrier excuse for a development team than this one right here. They take customers complaints, shove them in their face like they are useless, assume everyone is wrong except their all mighty brain power, then swear and act like little children. It truly is a joke, and I hope your website enjoys the massive DDoS attacks it will be receiving for your blatant rudeness and general attitude toward your users. Enjoy your day asshats.

**Comment by fr34kyn01535** [comment]
I bet $10 the server won't give a fuck. Mashrien are you in? I am sorry @kaegann2, but you might aswell shove this customer complaints in your own face. You are by the way not a customer, not even a client, we are doing this for free and for fun, so go ahead ;)

**Comment by kaegann2** [comment]
Happily. Anything to make you retards day worse.

**Comment by Mashrien** [comment]
This'll actually be funny to see, wonder what our host is gonna do when you take them all down and offline aww /boohoo.

I've never understood the ungrateful mentality of people that get something for nothing.

**Comment by fr34kyn01535** [comment]
Day #1 of @kaegann2 DDoS attack. 
Who is kaegann2?

**Comment by kaegann2** [comment]
Ungrateful? Ha. You guys are more retarded than I originally thought. Doesn't surprise me though. I hope none of you actually work in it. Your professionalism is a joke. Using swear words then changing your messages minutes later to not look like the asshats you are. Please do the world a favor, never reproduce, and remove yourself from this planet. Please and thank you.

**Comment by Mashrien** [comment]
Professional IT /salute Professional Troll

**Comment by fr34kyn01535** [comment]
Might aswell be a Professional DDoSer

**Comment by kaegann2** [comment]
DDoS attack will do this place some good. Did you of a couple users that don't need your asshatism. Maybe if you s really helped people in the bug tracker you wouldn't have incidents like mine. Oh wait. That would be professional of you.

**Comment by fr34kyn01535** [comment]
Such professionalism, much wow, he even is the Prophet of asshatism, your parents are probably proud :)

**Comment by Mashrien** [comment]
Wait, prophet?! DDoS terrorist?

**Comment by kaegann2** [comment]
My parents would be proud. Actually pointing out asshats to the world instead of letting them walk all over people because they think they are so smart. Like I said. Do the world a favor and stop coding. Let some professionals take over.

**Comment by fr34kyn01535** [comment]
Are you interested in doing my job? I mean, if trolling others is not keeping you to busy :D Ask your parents if you are allowed to be on the computer for a few more minutes and i will explain you how to deal with trolls by having a fun time playing with them instead of letting them make you angry ;)
