### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketFoundation/Rocket#23]
Because reflection is not the solution :D (http://i.imgur.com/1oGVFTU.png)

**Comment by fr34kyn01535** [comment]
Done :D

**Comment by Minidoracat** [comment]
Thank u very much :D

**Comment by Minidoracat** [comment]
This is wrong
http://i.imgur.com/mjHPQUO.png 
Need to fixed to it
http://i.imgur.com/ugGGysn.png
