### ISSUE TITLE
Cannot Spawn Or Craft 3.8.6.0 Items With Rocket Installed In Servers

### ISSUE THREAD

**Issue by wcsgtfox** [RocketFoundation/Rocket#27]
Tried Crafting generators garages etc, tried also spawning them in. Just does not work!

**Comment by fr34kyn01535** [comment]
I am not able to reproduce, please try to reinstall Unturned 3 & Rocket and try it again.

**Comment by Zamirathe** [comment]
I am unable to reproduce either.  Works fine with the last update and last beta install of Rocket.
