### ISSUE TITLE
"This server is running modified files"

### ISSUE THREAD

**Issue by Lazzeking** [RocketFoundation/Rocket#3]
Hi,
As i said in the title, when i'm joining my server it says " This server is running modified files"
i Don't know what should i do? i've done something wrong? 
The Installation went without problems, even in the Console nothing is showing.

I didn't have plugins because i deleted them , i was thinking that one plugin caused the error, but not ...

Thanks 
-Lazzeking

**Comment by fr34kyn01535** [comment]
Try to re validate the game so that its in a clean state, and then run the Rocketloader again.

**Comment by Lazzeking** [comment]
Ok now it seems working, 
about the resources.asset error i shouldn't mind right?

Anyway Thanks man, you did a great job with Rocket ;)

**Comment by Lazzeking** [comment]
Anyway man, one last thing to ask you:
I can run a Custom map or only Devtest Map?

**Comment by fr34kyn01535** [comment]
Sure you can run custom maps, Rocket does not restrict it at least. The resource.asset error can be ignored yes. You are welcome!

**Comment by Lazzeking** [comment]
Man i don't know but i've tried to set a Custom map, but it again shows the : "This server is running modified files" Error.
Maybe i've done something wrong?
