### ISSUE TITLE
Cardinal Points to other Langs

### ISSUE THREAD

**Issue by Lion4K** [RocketFoundation/Rocket#34]
Translation Id="command_compass_facing_private" Value="You are facing {0}" />
  Translation Id="command_compass_north" Value="North" />
  Translation Id="command_compass_east" Value="East" />
  Translation Id="command_compass_south" Value="South" />
  Translation Id="command_compass_west" Value="West" />

Like I presume that it Sums the North and East and form NorthEast as reply.
but that does not work In portuguese.
North = Norte
East = Leste
NorthEast = Nordeste

By suming the 2 words the reply is:
NorteLeste

and should be: Nordeste

So it is in need of:

command_compass_Northeast
command_compass_Southeast
command_compass_Southwest
command_compass_Northwest

so we can make better translations.

**Comment by fr34kyn01535** [comment]
Fixed
