### ISSUE TITLE
Grief protection injection points

### ISSUE THREAD

**Issue by Mashrien** [RocketFoundation/Rocket#38]
In DamageTool--Fire, near the bottom of the function he checks tags to determine the type of object being damaged. At this point the object and player are already known and this is the ideal point of interception.  Directly after the two 'else if' opening braces, a call to Rocket containing the "damageInfo" object in it's entirety would facilitate 80% of the work required.  The other point of injection is (I believe, anyway) in BarricadeManager--dropBarricade. There all we'd have to do is pass the player and structure being placed.

        else if (((Component) damageInfo.P).get_tag() == "Barricade")
        {
          // Need call to Rocket here, return if function returns false
          s2 = EPlayerHit.BUILD;
          if (((Object) damageInfo.P).get_name() == "Hinge")
            BarricadeManager.damage(damageInfo.P.get_parent().get_parent(), K, X);
          else
            BarricadeManager.damage(damageInfo.P, K, X);
        }
        else if (((Component) damageInfo.P).get_tag() == "Structure")
        {
          // Need call to Rocket here, return if function returns false
          s2 = EPlayerHit.BUILD;
          // ISSUE: explicit reference operation
          StructureManager.damage(damageInfo.P, Vector3.op_Multiply(((Ray) @F1).get_direction(), Y), F2, X);
        }

**Comment by fr34kyn01535** [comment]
As Nelson does not remember owner of barricades, and also doesn't forward them into the various methods where damage is triggered this would be a nearly impossible to write and maintain hack. Unless Nelson prepares this - it won't happen.

**Comment by Mashrien** [comment]
As I stated in the above text, we'd be responsible for recording who placed what structures.

We record who places their own items on a map.
When an item is received, we check that player's list of owned items, if .Contains(targetStructure) == false, then damage is ignored.

#blamenelson here is just disallowing a really widely desired addition, not to mention delaying making Rocket the absolute must-have over vanilla (not saying it isn't already, but this means vanilla simply wouldn't exist anymore.)
