### ISSUE TITLE
rcon server command error

### ISSUE THREAD

**Issue by tiririca** [RocketFoundation/Rocket#39]
Hello, i have a problem when using rcon, i connect and use a command, but the command arguments are mixed with command name, for example when i use the command: "say test" the server do the command say with the arguments: "say test" and then broadcast "say test" instead "test", same for the give command, if i do "give player/10/5" the server returns: "cannot find player called (give player)". I'm trying to create a tool using rcon and can't do it because of that issue =(

**Comment by einkelflugle** [comment]
I have the exact same issue. I'm using Rocket v3.3.0.0 with Unturned 3.9.1.0.

**Comment by tiririca** [comment]
I'm used the same, but i tested the 3.2.1.0 for Unturned 3.9.0.1 and have the same error.

**Comment by fr34kyn01535** [comment]
fixed
