### ISSUE TITLE
Joining Server Error when Lauching Rocket

### ISSUE THREAD

**Issue by PaperMario** [RocketFoundation/Rocket#42]
Hey guys. I started Rocket running On my server on 3.3.0.0 for Unturned 3.9.3.0 but when i joined my server it says "This Server is running Modified Files". Can someone Help me?

**Comment by h4ugen** [comment]
CONFIRMED, this server is running modified files. gosh...

**Comment by h4ugen** [comment]
^^

**Comment by PaperMario** [comment]
thats the point...im using Rocket for Unturned and for other people, they have people joining there server using rocket. so im wondering if i messed up on something

**Comment by h4ugen** [comment]
Uhm, are you sure they are using rocket? they could just have uninstalled it for the moment being...

**Comment by h4ugen** [comment]
Well it's something messed up that affects some of us at least, kinda shit...
Just want to play -.-

**Comment by fr34kyn01535** [comment]
Reinstall Untruned, Reapply Rocket.

**Comment by h4ugen** [comment]
nop didnt work
