### ISSUE TITLE
Server crashs when i try joining server

### ISSUE THREAD

**Issue by LazyPiggyHD** [RocketFoundation/Rocket#433]
http://pastebin.com/dsfF1zVA

and the server crashes =(

**Comment by Trojaner25** [comment]
The rocket version you are using is incompatible with the unturned version. Are you using the latest rocket version?

**Comment by LazyPiggyHD** [comment]
yes

**Comment by Kirollos** [comment]
One of the plugins you are using is incompatible with [rocket 4.5.0.0](https://rocket.foundation/viewtopic.php?f=44&t=449)

**Comment by fr34kyn01535** [comment]
Yep, its an outdated plugin.

**Comment by LazyPiggyHD** [comment]
i just updated all my plugins
