### ISSUE TITLE
TPS always zero

### ISSUE THREAD

**Issue by SergiX44** [RocketFoundation/Rocket#435]
From some build of rocket at the command /tps it says always 0

**Comment by JzJad** [comment]
"From some build of rocket" Please elaborate... What version, and does this happen even from a clean world?

**Comment by SergiX44** [comment]
Not know the precise build, certainly after 4.5.0.0

**Comment by JzJad** [comment]
Is it just visual, does the server run fine but its reading 0, or are the players lagging with a high ping?

**Comment by sjkgames** [comment]
Hello，I have the same problem with Sergix44. Server vision is 3.11.6.0 Rocket vision 4.5.2.0.
Problem is High ping ，Tps 0 or 3. All Players Disconnect。

**Comment by SergiX44** [comment]
The players disconnections is a problem of power of your machine, not rocket, tps can't never be 0,  this is the bug.

**Comment by fr34kyn01535** [comment]
TPS will be removed in the new version of Rocket anyway. TPS is not a indicator for lag, but for LOAD.
