### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by Nicholaiii** [RocketFoundation/Rocket#436]
![Error](http://puu.sh/iTW2S/807ce9c934.png)

I get this on startup. Right after the "Done..." message. Newest build (#493)

**Comment by Mashrien** [comment]
Given it's pathfinding, it's probably not, but have you tried running a clean config with no plugins?

**Comment by Zamirathe** [comment]
Is that the entire error?

**Comment by Nicholaiii** [comment]
Yes it was the entire error. I still have the error after updating to #505. I will try with a clean slate in an hour or so and report back

**Comment by fr34kyn01535** [comment]
thats a day ago

**Comment by Nicholaiii** [comment]
Yes, real life rudely intervened with my internet operations. I have however been trying several times, but a clean instance, on the same machine as the error was produced, just keeps crashing on me, so I can't report back on that. Running a completely fresh instance on my local machine gives me no errors.
