### ISSUE TITLE
Permissions GroupDependency

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#441]
Would this be possible to implement as a new feature?

http://pastebin.com/4c0TRFVG

This would allow to give special event rewards to players only applyed to specific groups.
Also would allow to remove specific players from groups but keep the "permissions" they already earned in the past from other events/rewards.

In the pastbin example fr34k when added to the terrorist group would be awarded with a group permissions that others would have not. But when added to the policeman group, that reward would not be available for him.

**Comment by fr34kyn01535** [comment]
Naa, beside its no xml / this is way to complicated, per user permissions would be easier here

**Comment by manuelbarbosa** [comment]
That would make a HUGE permissions per user file, this would allow much more combinations with the permissions group. Not that hard to implement imo.

**Comment by manuelbarbosa** [comment]
The pastbin is just XML lazy explanation, not a real one ofc.

**Comment by fr34kyn01535** [comment]
I don|t understand zour example, could you please make xml out of it and epxplain? Group hierarchy does already exist..

**Comment by manuelbarbosa** [comment]
Ok, I will make a example file to explain what I think would be cool. Keep this open.

**Comment by manuelbarbosa** [comment]
PLAYER A
PLAYER A
PLAYER A

**Comment by manuelbarbosa** [comment]
http://pastebin.com/GGiFmWiu

* PLAYER A : vip-elite, elite-champs-2015
* PLAYER B : vip-elite
* PLAYER C : vip-normal
* PLAYER D : 
* PLAYER E : vip-normal

### Example ###
**PLAYER A** has *elite-champs-2015* because he is part of the *vip-elite* group (GroupDependency) but **PLAYER C** does not because he is only *vip-normal*. **PLAYER D** is on the *elite-champs-2015* but also does not have the GroupDependency. If for some reason **PLAYER D** is placed back in the *vip-elite* he will be also be able to use the  *elite-champs-2015* permissions.

**PLAYER B** is part of the *vip-elite* but he did not get the reward from *elite-champs-2015* so dependency does not apply to him.

**PLAYER E** is on the *vip-normal* group that has no dependency, so its treated normally.

### Implementation ###
Before applying a group to the player, just check if the current player has the GroupDependency of that specific group. Pretty simple.

**Comment by fr34kyn01535** [comment]
I dont have any clue what you want from me, finising the sentence with pretty simple does not make it easier..

**Comment by manuelbarbosa** [comment]
I deleted that comment, it was a mistake.

**Comment by fr34kyn01535** [comment]
So he just gets a permission if he is in another group?
I don't get this manuel, its "pretty simple", create new groups for events & let them inherit the old groups - done

**Comment by manuelbarbosa** [comment]
Yea, that would work but if u have like 5 different rewards, everytime the player leaves the VIP group I will have to remove the member from all 6 groups (elite + 5x rewards).

That way I will keep the member in the reward groups and only remove him from the VIP group that all 6 rewads depend on.

**Comment by Nicholaiii** [comment]
I don't find this particularly useful myself, but it highlights the fact that it might be a good idea to allow plugin developers to override Rocket's permissions handler in order to make custom permissions systems, like how it functions in Bukkit eg

**Comment by fr34kyn01535** [comment]
#453
