### ISSUE TITLE
Someone that connects dosnt show anymore

### ISSUE THREAD

**Issue by Logan7432** [RocketFoundation/Rocket#442]
Every Since Nelson released a little update when players join my server it dosnt say they connect anymore... i really liked this feature. Every Rocket Command Works but When someone joins the server it dosnt say they disconnected or connected PLEASE FIX SOON!

**Comment by fr34kyn01535** [comment]
This will not be a feature in the upcoming reworked version anyway. No fix, find a plugin for this.
