### ISSUE TITLE
RCON not working

### ISSUE THREAD

**Issue by SergiX44** [RocketFoundation/Rocket#444]
As the title, here the problem:
![KSUploader](http://ksu.sergix44.ovh/143696019666.png)

**Comment by Trojaner25** [comment]
Did you connect to the correct port? Which protocol type did you use? SSH? Telnet? Raw?

**Comment by SergiX44** [comment]
see the screen, raw

**Comment by Trojaner25** [comment]
Oh, sorry, didn't see the bottom right

Do you maybe have a kind of firewall which may prevent connections?

**Comment by SergiX44** [comment]
Nope, it's on a developing machine with firewalls & co deactivated

**Comment by Firestorrrm** [comment]
Let's give a warm round of applause to the Rocket developers who fixed something that didn't need to be fixed.

**Comment by fr34kyn01535** [comment]
@Firestorrrm who fixed what? The old RCON was broken. The new works.
@SergiX44 Its probably a firewall issue, if you don't see something in the log file..

**Comment by Kirollos** [comment]
Apparently, loading rocket with no plugins doesn't start the RCON listener. Loading rocket with "at least" one plugin starts the RCON listener with no problem.
Without any plugin:
![](https://camo.githubusercontent.com/db9ef72b68dd898f0edb69be91906f02b9e58e88/687474703a2f2f692e696d6775722e636f6d2f6f7062655148462e706e673f31)

With "an empty" plugin:
![](https://camo.githubusercontent.com/df5a0b40c856eb0d631db11e3e75f0c7204bb695/687474703a2f2f692e696d6775722e636f6d2f6f73666b5274502e706e673f31)

**Comment by SergiX44** [comment]
@Kirollos i confirm that
