### ISSUE TITLE
color permissions showing blueish color again

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#445]
color.#FF7519

should be orange, and its showing blueish in-game

http://www.w3schools.com/tags/ref_colorpicker.asp

**Comment by fr34kyn01535** [comment]
Does a message with a color in chat does the same?

**Comment by manuelbarbosa** [comment]
other colors work normally, only that value show as blue

**Comment by Ollie262** [comment]
Did you add someone to more than one group? I found I made this mistake when I had myself added to two different groups.
