### ISSUE TITLE
Linux RocketLauncher bug

### ISSUE THREAD

**Issue by SergiX44** [RocketFoundation/Rocket#446]
when i start unturned+rocket on debian 32bit, he throw me this exception
![linux](http://i.imgur.com/gZkHzZB.png)

i've also tried to rename the unturned executable, but nothing of different happen.

**Comment by Trojaner25** [comment]
Try to verify your installation, you are maybe missing a file

**Comment by SergiX44** [comment]
I've tried to validate installation, i've also checked the start.sh and also tried to launch directly the RocketLancher executable, it don't give errors but the servers doesn't starts.

**Comment by Kirollos** [comment]
I was told that Rocket only works on Unturned x86. Try installing Unturned x86 instead.

**Comment by SergiX44** [comment]
on debian 32 bit i can only run unturned x86 ....

**Comment by Kirollos** [comment]
Is start.sh in unturned's root directory already?

**Comment by fr34kyn01535** [comment]
Unturned server only works with x32 afaik. Are you using the Linux Beta build? Did you follow instructions in start.sh? You seem to not have configured the paths properly. The linux build & scripts are not a easy drop in & done solution - a little bit of knowledge & interest is required to get it working..
