### ISSUE TITLE
Error #508

### ISSUE THREAD

**Issue by DevLeeo** [RocketFoundation/Rocket#447]
This error has occurred when i try to start server with new rocket version #508

http://i.imgur.com/ZCR7kPL.png

http://i.imgur.com/28UWefp.png

My UnityEngine.dll is a more recent

**Comment by Zamirathe** [comment]
Validate your Unturned files and reinstall Rocket.  Make sure you copy over all the dlls.

**Comment by Trojaner25** [comment]
What do you mean with "My UnityEngine.dll is a more recent"?
