### ISSUE TITLE
Rocket error on startup

### ISSUE THREAD

**Issue by skylarcoolya** [RocketFoundation/Rocket#452]
I get this bad image error on startup everything still works other than i cant load any plugins I don't even need any plugins in to get the error.

![image](https://cloud.githubusercontent.com/assets/10287418/8734336/621d5370-2bd7-11e5-9718-faac3ec59cd3.png)

**Comment by Zamirathe** [comment]
Revalidate your Unturned files, make sure you have the latest copy of Rocket, and reinstall Rocket.

**Comment by manuelbarbosa** [comment]
Im getting the same problem, this is a Rocket Problem but not a critic one.

**Comment by fr34kyn01535** [comment]
Check the contents of your plugin & libraries folder to contain proper .dlls.

**Comment by skylarcoolya** [comment]
i have had this problem for past 2-3 updates and i have already redone it before and its problem for me because i cant load plugins anyone have a solution
