### ISSUE TITLE
Broadcast command don't work with multiple words

### ISSUE THREAD

**Issue by DevLeeo** [RocketFoundation/Rocket#454]
![image](https://cloud.githubusercontent.com/assets/10111205/8740180/fc3f83e4-2c1b-11e5-9eee-5a56d093929d.png)

**Comment by Zamirathe** [comment]
Working a intended.  Put your entire sentence in quotes.  fr34ky, might recommend taking this out for the broadcast command only if possible.

**Comment by DevLeeo** [comment]
Hmmm, ok.

**Comment by fr34kyn01535** [comment]
Mhm, how should people change the color then?
Wouldnt /broadcast <color> [message] [more words] confuse them?

**Comment by fr34kyn01535** [comment]
Fixed. Changing /broadcast to [color] <message>
