### ISSUE TITLE
Can u help me

### ISSUE THREAD

**Issue by liyu4598239112** [RocketFoundation/Rocket#455]
I want make a plugin,but I can't use CsteamID, I think it may in steamworks.dll,but a can't find it ~ can u give me this dll??

**Comment by DevLeeo** [comment]
Assembly-CSharp-firstpass.dll

**Comment by liyu4598239112** [comment]
let me try~~

**Comment by liyu4598239112** [comment]
Thank u very much!!!!!

**Comment by DevLeeo** [comment]
:)
