### ISSUE TITLE
ArgumentException

### ISSUE THREAD

**Issue by EdwardPB13** [RocketFoundation/Rocket#457]
So yesterday I installed Rocket (lastest version) and TPA, Home and Givekit plugins. At first startup, the server ran perfectly with Rocket and other plugins but then I decided to change some Kits in the Givekit config file. After that I start the server and get this error. I don't know if it's because I messed up the Givekit config or not ( I'm pretty sure I didn't). So, any help would be appreciated. 
![rocketerror](https://cloud.githubusercontent.com/assets/13400053/8764409/b6120b20-2e01-11e5-87af-42a287bb0cd0.png)

**Comment by Trojaner25** [comment]
That's a plugin specific issue, not Rocket specific

**Comment by fr34kyn01535** [comment]
Propably a problem with one of the translation files, having a key doubled

**Comment by EdwardPB13** [comment]
Thanks guys but turns out it was me. I accidentally repeated the "Say" command in Command.dat :P
