### ISSUE TITLE
rocketplayer.Inventory.Clear();   Error

### ISSUE THREAD

**Issue by liyu4598239112** [RocketFoundation/Rocket#460]
I use rocketplayer.Inventory.Clear(),when player death,but sometime the player will drop some strange thing when he death,such as  magazine,Sunglasses or clothing
![is 9ggg17 2p_ u l5_ p](https://cloud.githubusercontent.com/assets/3618179/8771039/595e4c5c-2eee-11e5-9b35-d2010fae7817.png)

error like this

**Comment by fr34kyn01535** [comment]
Method will be removed in next version
