### ISSUE TITLE
Unplayable? - Unturned 3.9.4.0 - Newest Rocket

### ISSUE THREAD

**Issue by JDarkMatteR** [RocketFoundation/Rocket#47]
After installing Rocket 3.3.0.0, my game became unplayable. The game loads, but only displays the outside of the farmhouse, with all buttons unclickable, except for the stats. I also posted this in the Unturned bug reports. Anybody who can help me, thank you!

http://steamcommunity.com/app/304930/discussions/9/611703898448904593/

**Comment by lightphoenix2** [comment]
Please read the instruction : https://github.com/RocketFoundation/Rocket/wiki/Installing-Rocket

Note: Installing Rocket on your Steam client will make the game unplayable

If you can set up Rocket in your Server Folder or a separate folder besides your Steam client folder , if you wished to play Unturned.
