### ISSUE TITLE
NRE on UnturnedChat.Say if running a command alias from console.

### ISSUE THREAD

**Issue by cartman-2000** [RocketFoundation/Rocket#471]
I get a NRE error on UnturnedChat.Say if the command is ran from it's alias on the console. It works properly if the command is ran from the full command name and not the alias.

From a little plugin that I wrote for my server to reimplement the tps cap that used to be in Unturned(so the server doesn't sit there always eating up a full core of cpu.).
```
>limittps
<TPS> - Limits the server tps/fps to the value set in the command. 0 disables th
e TPS cap.
>ltps
An error occured while executing command /ltps : System.NullReferenceException:
Object reference not set to an instance of an object
  at Rocket.Unturned.Chat.UnturnedChat.Say (IRocketPlayer player, System.String
message, Color color) [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Chat.UnturnedChat.Say (IRocketPlayer player, System.String
message) [0x00000] in <filename unknown>:0
  at FPSCap.CommandLimitTPS.Execute (IRocketPlayer caller, System.String[] comma
nd) [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Commands.UnturnedAliasBase.execute (CSteamID caller, System
.String command) [0x00000] in <filename unknown>:0
```

**Comment by fr34kyn01535** [comment]
Btw. Did you find a proper targed FPS that ran smooth? Thinking bout implementing this into Rocket

**Comment by fr34kyn01535** [comment]
Can't replicate with built in commands, how is ur implementation

**Comment by cartman-2000** [comment]
It works properly when you run the command in the console with the commands main name, but it doesn't when it's run by the command's alias. The commands main name for the command that I tested it with is limittps, which works, and the alias is ltps, which doesn't work.

And by looking at the code in the UnturnedCommandBase.cs file, this if statement isn't in the UnturnedAliasBase.cs file.
https://github.com/RocketFoundation/Rocket.Unturned/blob/master/Commands/UnturnedCommandBase.cs#L99


As for the TPS/FPS cap, the original cap was set to 60TPS, which is good enough for most cases, and works the best for my server's. The difference in cpu usage from 60TPS to 30TPS isn't really noticeable, and the TPS tends to fluctuate more if the server can't keep up with TPS set to 30. Something higher than 60TPS doesn't really give you any extra performance(In the dev ping counter, or apparent lag on the server.) in my experience, while on the other hand it would raise the cpu usage of the server.

Something like this could technically be added to the rocket core, as it's a part of unity itself, and not a part of Unturned. The TPS of the server can be set with a single line of code.
"Application.targetFrameRate = 60;"

The code for my plugin can be found here. It allows a default TPS to be set, and to be able to change it on the fly by command when the server is running.
https://github.com/cartman-2000/FPSCap

**Comment by fr34kyn01535** [comment]
Fixed the issue, thanks.
Yea i know about targetFrameRate, was just thinking that increasing it could make network better..
