### ISSUE TITLE
XMLNS Error In Console Upon Server Startup

### ISSUE THREAD

**Issue by Neefgi** [RocketFoundation/Rocket#472]
Ever since about early morning yesterday (July 26th) I got a bunch of red errors on my Unturned 3.11.9.1 server running Rocket. Upon startup, my MOTD an DeathMessages plugin did not work, as well as the chat colors I put in the permissions.config.xml file. On startup it says "InvalidOperationException: <Permissions xmlns=''> was not expected - System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot (System.Xml.Serialization.XmlTypeMapping rootMap) as well as many other errors. Also, whenever someone types something in game chat, I get the same red error in my console : 
Assembly-CSharp >> Exception in askChat: System.NullReferenceException: OBject reference not set to an instance of an object at Rocket.Core.Permissions.RocketPermissionsManager.GEtGroups (IRocketPlayer player, Boolean includeParent Groups) [0x0000] in <filename unknown>:0 at Rocket.Core.Permissions.RocketPermissionsManager.GetPermissions (IRocketPlayer player) [0x00000] in <filename unknown>:0 at Rocket.Unturned.Chat.UnturnedChat.handleChat (SDG.Unturned.STeamPlayer steamPlayer, EChatMode chatMode, UnityEngine.Color& incomingColor, System.String message) [0x00000] in <filename unknown>:0

Idk if it's because of the new Rocket update or what but I don't know how to fix it and most of my advanced Rocket commands and permissions don't work. Any fix is very appreciated, thank you :).

**Comment by cartman-2000** [comment]
The root tag for the permissions config file changed from "Permissions" to "RocketPermissions", in the Permissions.config.xml file.

**Comment by Neefgi** [comment]
So all I have to do is change my permissions from Permissions to RocketPermissions?

**Comment by Neefgi** [comment]
Thanks a bunch, cartman-2000!
