### ISSUE TITLE
Logging to file dosen't work in Rocket 4.6

### ISSUE THREAD

**Issue by cartman-2000** [RocketFoundation/Rocket#473]
None of the stuff in the server console gets logged to file(no log file created in the Logs directory.). It still doesn't log anything if you try to create the Rocket.log file manually.

There's also a typo in the log file move code for the log files(missing forward slash.), that rolls the log when the server starts, so the rolled log file gets placed outside of the Logs directory.

**Comment by fr34kyn01535** [comment]
Fixed
