### ISSUE TITLE
Server Won't Save With Specified Time?

### ISSUE THREAD

**Issue by Neefgi** [RocketFoundation/Rocket#474]
In my Rocket.config file under Servers/Server name/Rocket/Rocket.config, I have the "Automatic Save Interval" set to 100 seconds. So, I should expect that the server saves the map and inventories every 1 minute and 40 seconds, correct? Yet, when I open Rocket Manager and my server starts up, all my Commands.dat load up normally, yet another line pops up that says "This server will automatically save every 1800 seconds." Except, I don't want every 30 minutes, I want 100 seconds, is there anyway to fix this? I know I can type "save" in console, but that requires me to physically be at my computer. I suppose this isn't a terrible issue, since I have the automatic save interval set to 7200, which means the server will save every 30 minutes, 4 times per session. It's not horrible, but I'd much prefer what I put in the Rocket.Config. Any fix is very much appreciated, thank you :).

**Comment by Alvetore** [comment]
Yep! Same here! Attached screenshot of error i have with autosave
![screen](https://cloud.githubusercontent.com/assets/12498515/8934650/513d487a-3551-11e5-8fe8-a77517a29a78.PNG)

**Comment by fr34kyn01535** [comment]
I don't know guys, why nobody reads the damn wiki, but if you encounter any problems you should fresh install rocket. If you had done that you would have found out that the configs changed.

**Comment by fr34kyn01535** [comment]
![image](https://cloud.githubusercontent.com/assets/898145/8946792/10cd3ed8-3594-11e5-9d4f-ba1a36671f5c.png)

**Comment by fr34kyn01535** [comment]
![image](https://cloud.githubusercontent.com/assets/898145/8946801/2c973dc6-3594-11e5-9f0a-2a1e3e63bec7.png)

**Comment by Neefgi** [comment]
I'm sorry fr34kyn01535, I would, but I'm afraid of losing my server! I appreciate your help, thank you :)

**Comment by Alvetore** [comment]
I read wiki and did fresh install all of configs and getting error on screenshot. Autosaving configured in new configuration file.

**Comment by fr34kyn01535** [comment]
@Alvetore @Neefgi This is another issue and reported here #476
