### ISSUE TITLE
Color convert from hex (in chat)

### ISSUE THREAD

**Issue by doozzik** [RocketFoundation/Rocket#475]
Hi. Thanks for the source code of Rocket! And sorry for my English.

I saw a mistake in code, while you convert hex color like #ABC to #AABBCC.
I am not pro in programming, so i try to explain in my words.

Mistake contains in /Chat/UnturnedChat.cs at line 77.
" if(hexString.Length ==3) hexString+=hexString; "

I have googled and understand, that hex color like #123 must be converted to #112233, but not to #123123

If you want proofs of my words, i may try to make plugin with this function and check it.

**Comment by fr34kyn01535** [comment]
Didn't know that, just checked that in css and looks like you are right :D, I think i'll simply remove the 3 digit support.

**Comment by fr34kyn01535** [comment]
Fixed, still supported, thanks to Kirollos
