### ISSUE TITLE
/broadcast color issue

### ISSUE THREAD

**Issue by CLSMCSMII** [RocketFoundation/Rocket#478]
====Rocket Linux Beta Build:204====

first I try /help
[Rocket]
admin
broadcast            \<color\> \<message\>

I've tried all possibility I can imagine 

broadcast #FF0000 "TEST"
broadcast "TEST" #FF0000
and so on with or without quote.

 It still show text message in green.

**Comment by DronXa** [comment]
You need to use /R/G/B at the end of the broadcast message, broadcast doesn't work with colors so use Say instead. Example: Say Test123 /255/0/255

**Comment by fr34kyn01535** [comment]
Nope, this is wrong.
Either use
/broadcast red Hello
or
/broadcast #eee Hi
or 
/broadcast Hi

*fixed
