### ISSUE TITLE
Plugin OnReload with Command

### ISSUE THREAD

**Issue by Zamirathe** [RocketFoundation/Rocket#48]
Kind of like p.reload except to reload all plugins config files, so can edit the files and reload the config without having to restart the server.

**Comment by fr34kyn01535** [comment]
When implementing this i should also add a OnReload method to the interface..

**Comment by LazyPiggyHD** [comment]
best idea 2015

**Comment by Zamirathe** [comment]
Was implemented in the last major update with Rocket.  Closing this.
