### ISSUE TITLE
List in Configuration not changing correctly

### ISSUE THREAD

**Issue by Zamirathe** [RocketFoundation/Rocket#482]
So I use a list in my UconomyEssentials configuration (and in several others but I haven't tested them yet).  What I have noticed is that the list in the config file is added to the default list provided by the configuration in code.  I had to add in some code for my custom object list so that Distinct will run correctly and therefore delete all these duplicates.  There is a problem with this though.  If you remove something from the list, it doesn't get removed by the code as it is still in the list from the default setting.

What needs to happen is what Rocket used to do.  If there is a config file, just load in the config file and overwrite all fields on the configuration.  This is currently working fine for fields that are simple like string, bool, uint and such, but lists are just doing a .Add and not overwriting.

To show what is going on.

Default config list:
```xml
<PayGroups>
    <Group DisplayName="all" Salaray="1.0" />
    <Group DisplayName="admin" Salary="5.0" />
    <Group DisplayName="moderator" Salary="4.0" />
    <Group DisplayName="guest" Salary="1.0" />
  </PayGroups>
```

New config list:
```xml
<PayGroups>
    <Group DisplayName="admin" Salary="5.0" />
    <Group DisplayName="moderator" Salary="4.0" />
    <Group DisplayName="guest" Salary="1.0" />
  </PayGroups>
```

Running some checks code wise and getting .Distinct( new CustomGroupComparer()).ToList() on it I had it output the name and salary in the paygroups and I still get:
all 1.0
admin 5.0
moderator 4.0
guest 1.0

The all portion was removed in config, but it is still being added in the code as it was there to begin with from the default.  Short of removing the default from the code, I cannot fix this.  If I do that, then what is the point of having a default anyways?

**Comment by Zamirathe** [comment]
I confirmed this affects more than just my plugins.  This also affects MessageAnnouncer, ZaupTextCommands, Kits...

**Comment by fr34kyn01535** [comment]
Fixed by requiring IDefaultable, containing LoadDefaults. To use, add the method from the interface and set all the attributes to defaults within this method.
