### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Ammodex** [RocketFoundation/Rocket#485]
Today was updated and Rocket Unturned. I've updated your server, and when you start it began to appear the error.
![er1](https://cloud.githubusercontent.com/assets/12857841/9020676/7b5b4290-383c-11e5-91e2-3bedad2618f1.png)
![er2](https://cloud.githubusercontent.com/assets/12857841/9020678/88ab1632-383c-11e5-8838-022a1769797e.png)
Plug-ins do not work in the game . When you enter / kit survival writes that there is no such command

P.S: Sorry for my English, I know it is very bad .

**Comment by Ammodex** [comment]
I forgot to write , I just updated all the plugins .

**Comment by Alvetore** [comment]
Delete your permissions file and let server to create new one. Then configure it and start server.

**Comment by Ammodex** [comment]
Already I have done. But how am I going to configure permissions and server configuration?
