### ISSUE TITLE
Rocket Manager Server Restart Warning Doesn't Warn In Server?

### ISSUE THREAD

**Issue by Neefgi** [RocketFoundation/Rocket#487]
I don't know if it's because of the new Rocket v4.0, but I'm not sure how to configure the 120 second pre warning for the automatic server restart. In my Rocket Manager, my server restarts every 2 hours, and I configured it to warn players 120 seconds before restart, but it doesn't happen? Has this been taken out or no? Thanks in advance :)

**Comment by Zamirathe** [comment]
Rocket Manager isn't part of Rocket.  Please post in the forum thread for this to notify the developer.
