### ISSUE TITLE
Rocket. 4.6.0.0 My opinion

### ISSUE THREAD

**Issue by ZTAkira** [RocketFoundation/Rocket#489]
Hello , I would like to say that I hated The New Rocket 4.6.0.0 , no plugin those I wore it works now, and most are not updated , I simply hated the new rocket again, and if you do not upgrade to old version that worked with old plugins will give up service to you , I am disappointed .

**Comment by katanavn** [comment]
rocket 4.6.0.0 just killing my server now .... i can't wait while everybody ask for the plugins
