### ISSUE TITLE
Error on Rocket.Unturned.Utils.AutomaticSaveWatchdog.Start (aka AutoSave)

### ISSUE THREAD

**Issue by MarkLeong1997** [RocketFoundation/Rocket#494]
When the rocket server starts with the following error message:
[Error] NullReferenceException: Object reference not set to an instance of an object - Rocket.Unturned.Utils.AutomaticSaveWatchdog.Start ()

![screenshot_216](https://cloud.githubusercontent.com/assets/3318567/9034944/26409cf8-3a06-11e5-9d32-cfc11dd63ffe.png)

The server refuses to run auto-save.

Is there any other way to solve this problem?
I've tried to disable any plugins and reset to default configurations.

**Comment by fr34kyn01535** [comment]
Show me the contents of the file Rocket.Unturned.config.xml

**Comment by MarkLeong1997** [comment]
Here's the config file.
![screenshot_232](https://cloud.githubusercontent.com/assets/3318567/9059679/c48d123c-3ade-11e5-9b1d-c0e8964e94f1.png)

**Comment by fr34kyn01535** [comment]
>>I've tried to disable any plugins and reset to default configurations.
You clearly didn't.
