### ISSUE TITLE
Downloading of Rocket is not working

### ISSUE THREAD

**Issue by Alvetore** [RocketFoundation/Rocket#498]
All in title. Can't download Rocket through link and api. Rocket Manager can't download it too. Downloading is starting but it doesn't downloading...

**Comment by fr34kyn01535** [comment]
Apparently the build agents died because no space left :D 
https://ci.rocket.foundation/

**Comment by fr34kyn01535** [comment]
Ok, cleared sum logs, also fixed download taking too long to load.
