### ISSUE TITLE
Argument is out of range console error?

### ISSUE THREAD

**Issue by Neefgi** [RocketFoundation/Rocket#500]
For some reason my server is now saying "Argument is out of range" everytime someone connects to the server.
![argumentrange](https://cloud.githubusercontent.com/assets/13526894/9149045/4dd1ae28-3d4a-11e5-8cdd-391df23d58c9.png)
I don't know what it means, it's only everytime someone connects, nothing else, and it's with Rocket. I'm not sure if it's the new join/connection plugin, but I uninstalled it, and it still shows the error. Does anyone know what this means?

**Comment by Zamirathe** [comment]
Backup everything and set your server back to vanilla.  (Don't remove any of the save files, just validate files or copy over validated managed folder files.)  This includes removing all downloaded mods from the workshop.  Does it still give the error?  If it does, it is an Unturned error and needs to be reported to Nelson.  If not, reinstall Rocket and see if it comes back.  If still no, reinstall any workshop items one at a time to check for errors.

As I don't see anything referencing Rocket in that, I suspect it has something to do with either the level files (like barricades.dat) or a workshop item.  More than likely the latter.  (Like a barricade item not configured correctly that it tries to report to all players who connect that it exists.)

**Comment by Neefgi** [comment]
@Zamirathe how do I reset it back to vanilla without deleting my server? The thing with Rocket is that I installed it in a separate folder than my actual Unturned folder, so there's two. I'm also not really sure how to back it up.

**Comment by UzielTD** [comment]
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index - System.Collections.Generic.List`1[SDG.Unturned.SteamPlayer].get_Item (Int32 index)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

ERROR PLAYER IN MY SERVER DISCONNETING AFTER THEY JOIN!!!

[12/9/2017 8:07:49 PM] [Info] JoinLeaveMessages >> Broadcast: [Member]jeff connected to the server.
[12/9/2017 8:07:57 PM] [Info] JoinLeaveMessages >> Broadcast: [Member]jeff disconnected from the server.
[12/9/2017 8:07:57 PM] [Info] Disconnecting: PlayerID: 76561198197701630 Name: vinunleaded Character: [Member]jeff
[12/9/2017 8:07:57 PM] [Error] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index - System.Collections.Generic.List`1[SDG.Unturned.SteamPlayer].get_Item (Int32 index)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()
PLEASE FIX THIS

**Comment by persiafighter** [comment]
@UzielTD That bug is not rocket related. Also, create a new issue... don't comment on dead issues.
