### ISSUE TITLE
Permissions Setting Bug (/p.set command)

### ISSUE THREAD

**Issue by Pattedelapinou** [RocketFoundation/Rocket#501]
Hi ! 

So i have a server. Everything is working fine (plugins, rocket..) My server is growing pretty fast so i made some VIPs ranks and kits to buy on my website. I used to get their steam64ID and type it to the permissions file then restart the server each midnight. Someone told me that i could used the /p.set command. 

When i use it on someone it says that it added this person to the group but for some reasons after i use the p.set command my permissions file reset to the basic one. ( the one with two groups -> default and VIP) I dont have any error in the console. So i dont see from where the problem come from. I also reinstalled rocket few times.

**Comment by cartman-2000** [comment]
p.set is a permission for a player to have to be able to set a player to a group.

Something like that shouldn't happen unless you had some sort of syntax error in the permissions xml file.

**Comment by cartman-2000** [comment]
And this also affects plugin configs too.
