### ISSUE TITLE
Server Errors

### ISSUE THREAD

**Issue by clericlocus** [RocketFoundation/Rocket#502]
This is a vanilla server with only Rocket on it, and it returns this error upon starting: https://gyazo.com/91f917d9869058388e599e32d51f4cef

**Comment by Kirollos** [comment]
I think you should read the error first before creating an issue. The error says that rocket has failed to deserialize Rocket.Unturned.config.xml, And I think the file is empty. I'd suggest deleting all your configuration files and let the server generate them.
