### ISSUE TITLE
Bug with prone/crouch, and not able to place floors on the map.

### ISSUE THREAD

**Issue by cartman-2000** [RocketFoundation/Rocket#504]
There's an issue of getting stuck in crouch or prone when you go to it, And you're not able to set floors on the map.

(the car lights one was a bind problem on my client.)

**Comment by alexr03** [comment]
Its a unturned bug.

**Comment by cartman-2000** [comment]
No it's not in my case, Everything works fine if I run the server in vanilla, but it has these bugs when trying to run the server with rocket on it.

And there's another bug too with rocket and the update, your not able to set floors down anywhere on the map to build on the map.

**Comment by cartman-2000** [comment]
Hmm, I got it working on my test server, and got it working on my main server's transferring that map to the main ones.

**Comment by fr34kyn01535** [comment]
So its a bug with the old map?

**Comment by alexr03** [comment]
I don't think so, I believe its a bug with the game because it happens with me on both maps even on vanilla, and/or rocket installed with it
