### ISSUE TITLE
Error On Startup with Rocket Unturned v.4.6.1.1 for Unturned v3.12.0.0 

### ISSUE THREAD

**Issue by TheChosenOneTM** [RocketFoundation/Rocket#506]
Happens on startup every time. The loading bar makes it to the end, but doesn't connect to the server.

Rocket Unturned v4.6.1.1 for Unturned v3.12.0.0

Successfully set name to Working!
Successfully set map to PEI!
Successfully set port to 27015!
This server will automatically shutdown in 86400 seconds (8/15/2015 10:13:59 PM
UTC)
ArgumentException: The thing you want to instantiate is null. - UnityEngine.Obje
ct.CheckNullArgument (System.Object arg, System.String message)
UnityEngine.Object.Instantiate (UnityEngine.Object original)
SDG.Unturned.Level.OnLevelWasLoaded (Int32 id)

**Comment by cartman-2000** [comment]
Have you tried running the server on a fresh map?

**Comment by TheChosenOneTM** [comment]
How do I change it to a new map?

**Comment by TheChosenOneTM** [comment]
I changed the map and the error doesn't pop up, but now when I try to connect it says loading and goes back to the menu.

**Comment by TheChosenOneTM** [comment]
I reinstalled the game to get a new copy of the map and deleted the old version, but I still receive the error. I also installed two maps from the workshop and one gave the error and the other got rid of the error, but wouldn't let me load into the server. Is there a correct way or a better way to get a fresh map rather than reinstalling?

**Comment by TheChosenOneTM** [comment]
After messing with things I have found out that in order to join the server I cant have anything in the workshop folder. How can this be fixed?

**Comment by TheChosenOneTM** [comment]
After messing around even more. I found out it is not a server problem now. I cant connect to any server with workshop mods. I hosted the server and got my friend to connect with workshop stuff installed on the server, but when I tried to connect all it says is loading. So pretty much the new problem is that I cant connect to servers with workshop stuff installed. Any fixes?

**Comment by fr34kyn01535** [comment]
I found problems with a few of my mods, some are just broken...
