### ISSUE TITLE
Pagination possible with p command?

### ISSUE THREAD

**Issue by Zamirathe** [RocketFoundation/Rocket#51]
I have noticed that if you have a lot of commands available to you with multiple plugins and a member of multiple groups, you easily hit the max character limit with the p command.  This means I can't see all of the commands that I have the ability to use for my group(s).  Can this be paginated at all without hitting the chat history limit problem?

**Comment by cartman-2000** [comment]
You should be able to without hitting that chat limit. You could either do it by splitting it into multiple chat messages or through pagination.

**Comment by Zamirathe** [comment]
Thank you, this working good.  :)
