### ISSUE TITLE
"this server is running a modified version of game"

### ISSUE THREAD

**Issue by leonardosnt** [RocketFoundation/Rocket#510]
![image](https://cloud.githubusercontent.com/assets/13869336/9357041/0ac095b2-465b-11e5-9c5c-3fb8fffb42ba.png)

![image](https://cloud.githubusercontent.com/assets/13869336/9357051/1dac9842-465b-11e5-804d-a9dfde6bccc8.png)

**Comment by fr34kyn01535** [comment]
the server is running a modified version of game
