### ISSUE TITLE
new version of the rocket does not work

### ISSUE THREAD

**Issue by Xetrick** [RocketFoundation/Rocket#512]
well the new version of the rocket does not work 3.12.1.0 I install update everything and says this server is running a modified of version of the game help pls epic bug and if and actualize the game and it happens to everyone sorry for my english and the 3.12.1.1 :3

**Comment by TheChosenOneTM** [comment]
Having the same problem.

**Comment by Michael0100** [comment]
My server is also currently experiencing this issue.

**Comment by Michael0100** [comment]
I found out a server reinstall helped me and Rocket is now working, it should be all good now.
