### ISSUE TITLE
UnturnedPlayer is sealed

### ISSUE THREAD

**Issue by prestonvanloon** [RocketFoundation/Rocket#513]
I want to derive my own player class from UnturnedPlayer because .Equals does not work and needs to be overriden, but it can't be derived because it is sealed.

**Comment by Zamirathe** [comment]
It was sealed as deriving from it is silly.  Every player gets an UnturnedPlayer assigned to them when they connect.

What do you mean Equals doesn't work?  You can't do something like if (caller == player)?  It is working for me in my plugins just fine.  Both have to be UnturnedPlayer though.

If you want your plugin to have something that attaches to every player, look at the UnturnedPlayerComponent.  Anything derived from that will get attached on connect also.

**Comment by fr34kyn01535** [comment]
What are you talking about? Equals works & is implemented.
