### ISSUE TITLE
More rocket errors spamming console and players cant join

### ISSUE THREAD

**Issue by tenten8401** [RocketFoundation/Rocket#516]
This error is spamming the console:

`NullReferenceException: Object reference not set to an instance of an object - S
DG.Unturned.Block.write (System.Object objects)
SDG.Unturned.Block.write (System.Object[] objects)
SDG.Unturned.SteamPacker.getBytes (Int32 prefix, System.Int32& size, System.Obje
ct[] objects)
SDG.Unturned.Steam.accept (SDG.Unturned.SteamPlayerID playerID, Boolean isPro, B
oolean isAdmin, Byte face, Byte hair, Byte beard, Color skin, Color color, Boole
an hand, Int32 shirtItem, Int32 pantsItem, Int32 hatItem, Int32 backpackItem, In
t32 vestItem, Int32 maskItem, Int32 glassesItem, System.Int32[] skinItems, EPlay
erSpeciality speciality)
SDG.Unturned.Steam.onInventoryResultReady (SteamInventoryResultReady_t callback)

Steamworks.Callback1[Steamworks.SteamInventoryResultReady_t].OnRunCallback (Int
Ptr thisptr, IntPtr pvParam)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.Callback1:OnRunCallback(IntPtr, IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
SDG.Unturned.Steam:Update()`

**Comment by Golur** [comment]
Im getting the same error everytime someone tries to join

**Comment by tenten8401** [comment]
Worst part is they cant even join, the client just locks up.

**Comment by Golur** [comment]
Some of my buddies were able to join, Idk how

**Comment by tenten8401** [comment]
I was able to join once, but then it stopped

**Comment by Kirollos** [comment]
https://github.com/RocketFoundation/Rocket/issues/517
