### ISSUE TITLE
admin/unadmin not work

### ISSUE THREAD

**Issue by SergiX44** [RocketFoundation/Rocket#519]
simply the command admin <nick of the player connected> or admin <steam64id> not working, and also the unadmin. simply the console doesn't tell anything
![1440850302848](https://cloud.githubusercontent.com/assets/4172890/9561846/efdb3a72-4e57-11e5-9c59-ef5a71e2c593.png)

removed rocket, admin/unadmin working.
(If can help the server has webpermission activated)

**Comment by fr34kyn01535** [comment]
Does this answer your question? https://github.com/RocketFoundation/Rocket.Unturned/blob/master/Commands/CommandAdmin.cs

**Comment by SergiX44** [comment]
Oh, but now the question is how to admin or unadmin people when webpermission are activated?

**Comment by fr34kyn01535** [comment]
Why do you think its deactivated

**Comment by SergiX44** [comment]
if (!R.Settings.Instance.WebPermissions.Enabled)
if the webpermission is activate it doesn't admin people, right?
On webpermission file you can't set server admin, right?
With webpermission enabled you can't admin people from console, right?
??

**Comment by fr34kyn01535** [comment]
Yep.

**Comment by SergiX44** [comment]
So, how can i admin someone with webperm on?

**Comment by fr34kyn01535** [comment]
Not at all, Webpermissions makes it easy to manage multiple servers with permissions, for sake of security tho /admin is disabled, so changes in the webpermissions directly reflect onto the game servers. Imagine one of your mods making himself admin, then getting kicked out of staff - he'd still be admin everywhere.
