### ISSUE TITLE
TypeLoadException: Could not load type 'Rocket.Core.Serialisation.RocketPermissionsGroup' from assembly 'Rocket.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'. - 

### ISSUE THREAD

**Issue by kjcn** [RocketFoundation/Rocket#523]
TypeLoadException: Could not load type 'Rocket.Core.Serialisation.RocketPermissionsGroup' from assembly 'Rocket.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'. -

**Comment by fr34kyn01535** [comment]
Outdated plugin, i guess..
