### ISSUE TITLE
/god mode is not working

### ISSUE THREAD

**Issue by allenh015** [RocketFoundation/Rocket#54]
In the server cmd, it says 
NullReferenceException: Object Reference not set to an instance of an object.
What does it mean? Sorry 1st timer here

**Comment by h4ugen** [comment]
Yeap, confirmed. Godmode doesnt work for some reason.

**Comment by fr34kyn01535** [comment]
PLEASE use the latest beta and just report bugs on that. This is a duplicate to #53 and fixed.
