### ISSUE TITLE
Error on first loading Rocket

### ISSUE THREAD

**Issue by Zamirathe** [RocketFoundation/Rocket#55]
This was thrown by someone I was helping in TS.  New server, just installed Rocket with no plugins yet, first run to create Rocket files.

NullReferenceException: Object reference not set to an instance of an object
  at Rocket.RocketAPI.RocketPluginManager.Start () [0x00000] in <filename unknown>:0

Subsequent starts of the server did not throw the error.

**Comment by fr34kyn01535** [comment]
Can approve this

**Comment by fr34kyn01535** [comment]
Fixed
