### ISSUE TITLE
Debug plugins with a debugger

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketFoundation/Rocket#57]
There must be a way! For some reason i don't see Rocket or any of the plugins loaded as module in the debugger...
I searched the web but majority says they should come up even when dynamically loaded, must be something weird in Mono..

**Comment by robnauticus** [comment]
Please!

**Comment by fr34kyn01535** [comment]
rel https://github.com/angavrilov/ksp-devtools

**Comment by fr34kyn01535** [comment]
Here it is ;) https://github.com/RocketFoundation/Rocket/wiki/Debugging-Rocket
