### ISSUE TITLE
Website Forum Error

### ISSUE THREAD

**Issue by Zamirathe** [RocketFoundation/Rocket#59]
Got this error tonight when posting a topic or sending a pm.

[phpBB Debug] PHP Warning: in file [ROOT]/ext/tapatalk/tapatalk/event/main_listener.php on line 110: include_once(./mobiquo/push/TapatalkPush.php): failed to open stream: No such file or directory

The topic/pm does get through, but have to go back to see it as I get that error on a blank page.  Not sure if you were installing a plugin or anything to the forum.

**Comment by fr34kyn01535** [comment]
Should be fixed

**Comment by fr34kyn01535** [comment]
Is it?
