### ISSUE TITLE
Unlock Structures and Barricades information

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#61]
SDG.BarricadeRegion.K --- List of all Barricades Transforms
SDG.StructureManager.N --- List of all Structures Transforms

**Comment by manuelbarbosa** [comment]
I see you unlocked SDG.StructureManager.Structures

SDG.BarricadeRegion.Barricades and Barricades Data need to be set to static so it can be accessible

**Comment by fr34kyn01535** [comment]
No, you have to get the instance, i won't change variables to static because i can't track if nelson does ever instanciate them again.

**Comment by manuelbarbosa** [comment]
you need to unlock this then:

* BarricadeManager.BarricadeRegion[,] r;   (private static BarricadeRegion[,] r)

that would be probably our Instance

same goes for this one

* BarricadeManager.U;   (private static BarricadeManager U;)

that would be the BarricadeManager Instance
