### ISSUE TITLE
"Server running modified files." Bug

### ISSUE THREAD

**Issue by JDarkMatteR** [RocketFoundation/Rocket#65]
Whenever I attempt to connect to my Rocket server, I am pushed back to the starting screen and displayed the message. Help?

~I am running the latest Unturned and Rocket 3.4.1.0
Thank you.

**Comment by Zamirathe** [comment]
It means that the rocket version that was installed wasn't for the unturned version on your server.  Run the update on your unturned server again and do validate to install them cleanly.  Then reinstall latest Rocket beta.

**Comment by JDarkMatteR** [comment]
Thank you!
