### ISSUE TITLE
Typing /kit creates error in console

### ISSUE THREAD

**Issue by LazyPiggyHD** [RocketFoundation/Rocket#66]
'Rocket.RocketAPI.RocketPlayer.HasPermission'

what does this mean? and someone help me quick my players are getting pissed

**Comment by JDarkMatteR** [comment]
Yeah, Rocket updated. /Kit won't work for me either. Sorry~~~

**Comment by Zamirathe** [comment]
Please download the latest version of the plugin.  It was updated today.

**Comment by LazyPiggyHD** [comment]
alright thanks for the info i will do that :D

**Comment by LazyPiggyHD** [comment]
thank you for the info, helped alot cause it works ^_^
