### ISSUE TITLE
Random Error, also cant join

### ISSUE THREAD

**Issue by LazyPiggyHD** [RocketFoundation/Rocket#69]
Error in checkTimerSave: System.NullReferenceException: Object reference not se
 to an instance of an object
  at SDG.VehicleManager.save () [0x00000] in <filename unknown>:0
  at SDG.SaveManager.save () [0x00000] in <filename unknown>:0
  at Rocket.RocketFeatures.checkTimerSave () [0x00000] in <filename unknown>:0

**Comment by Zamirathe** [comment]
Do you get this error when you do /save in game or save from the console?

What do you mean you can't join?

**Comment by killahtomato** [comment]
This is also happening to me, it just spams this over and over. No saving, no commands being used.

**Comment by fr34kyn01535** [comment]
Set automaticsavetime to 0 is a temporary fix

**Comment by LazyPiggyHD** [comment]
i know how to fix it, just update your unturned server using steam cmd. and there you go!

**Comment by fr34kyn01535** [comment]
So this is not happening in latest Rocket?

**Comment by fr34kyn01535** [comment]
Not reproducable
