### ISSUE TITLE
RocketPlayer.GiveItem item quality

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#73]
RocketPlayer.GiveItem item quality

update RocketPlayer.GiveItem to add item quality (optional)

RocketPlayer.GiveItem(ushort itemId, byte amount, byte quality = 0);

**Comment by fr34kyn01535** [comment]
Where do you see this overload in nelsons methods?

**Comment by manuelbarbosa** [comment]
Item class gets a new parameter. I fixed this in Zamis feast plugin. I am out of the country so I can't tell u in the code where it is exactly

**Comment by fr34kyn01535** [comment]
While item has it, its not in trygiveitem...

**Comment by manuelbarbosa** [comment]
I will be back on the 6th I will try to figure it out and let you know. Don't worry about this enhancement.

**Comment by fr34kyn01535** [comment]
Items will now always spawn with 100%, unless the new parameter randomQuality is set to true (doesn't work with guns as described in #77)
