### ISSUE TITLE
Another lag bug

### ISSUE THREAD

**Issue by h4ugen** [RocketFoundation/Rocket#74]
When a player moves, it looks like he's flying.
This happens to every player on the server, and everyone sees the same happening.
This happened after updating to Rocket Beta 3.4.1.1 (#242) for Unturned 3.9.9.0
Happens on 3 servers, confirmed. It doesn't exactly look like he's flying, I would say that
99% of the time they're invisible, and 1% of the time they're flying.

**Comment by JohnnyChimpo420** [comment]
I have the same bug.

**Comment by h4ugen** [comment]
Every hoster I talk to also have this issue.

**Comment by JohnnyChimpo420** [comment]
Yeah, i am running vanilla right now to avoid this problem

**Comment by fr34kyn01535** [comment]
Since the description of this is not correct merged into #75
