### ISSUE TITLE
Pvp Doesnt work

### ISSUE THREAD

**Issue by bernas293** [RocketFoundation/Rocket#76]
Since the new update im having some problems on my server with the pvp, some players sometime can kiis others and sometimes not...

**Comment by silentnj** [comment]
Yup the same is happening to my server. some players are taking damage while others don't take any kind of damage, while other take damage,
im not sure if its the rocket problem or unturned patch problem.

**Comment by fr34kyn01535** [comment]
Can u please test this on vanilla before you report this, to make sure if its a rocket problem!?

**Comment by bernas293** [comment]
i think its not a rocket problem, beacaused i talked with otheres host server, and everyone is gettung this, so i think i really a unturned bug with the new version 3.9.9.0, almost sure that isnt rocket but is a unternd bug

**Comment by Frijolitomlg** [comment]
im having the same issue, but if the player dies or suecide they go back to normal until reconect
