### ISSUE TITLE
Can't see barricades on spawned vehicles

### ISSUE THREAD

**Issue by Zamirathe** [RocketFoundation/Rocket#79]
If you spawn in a vehicle and then place any barricade item on it, it places but it disappears.  Only when you log out and log back in can you see it.

I tried this driving around in the car to get the game to "see" the car, but still didn't show up.  It is like the server knows the barricade is there, but the client doesn't.

Unturned bug.  Happens in vanilla too.

**Comment by Kameron1** [comment]
It's a unturned glitch
