### ISSUE TITLE
Server Not showing up in game

### ISSUE THREAD

**Issue by trivera90** [RocketFoundation/Rocket#8]
When i start up the server with out rocket it shows up in game but as soon as i install rocket it wont show up.

**Comment by fr34kyn01535** [comment]
When i start up the server with rocket it shows up in game

**Comment by trivera90** [comment]
What could I be doing wrong that my server won't show up in game with rocket?

**Comment by trivera90** [comment]
i rolled back to a previous version of rocket and it showed up in game....
these lastest updates arent working for me. Still not showing up in game.

**Comment by fr34kyn01535** [comment]
Without any further info about errors & misbehavior this is not correct

**Comment by trivera90** [comment]
There are no errors that show in console, i can connect to the server completely fine and others can find the server in steam and also connect. The only problem is it wont show up in the in game server list. It shows up fine in the in game server list when rocket is not installed. so i figured it has to do with rocket. im using build 188 for now since this one works and shows the server in game.

**Comment by trivera90** [comment]
Tell me what you need to help me figure this out.

**Comment by fr34kyn01535** [comment]
Ok, latest version should have the fix, thank you for your patience!

**Comment by fr34kyn01535** [comment]
Confirmed to be fixed in #200
https://ci.rocket.foundation/job/RocketLoader/200/

**Comment by trivera90** [comment]
Thank you this one worked. :)
