### ISSUE TITLE
Unturned update 3.9.9.3 broke rocket mod based console messages.

### ISSUE THREAD

**Issue by cartman-2000** [RocketFoundation/Rocket#82]
This update broke any(That I have seen so far from testing.) rocket mod based message going to the console, but they still get logged correctly and show properly to the clients.

**Comment by falsechicken** [comment]
Yeah. Its known and is being worked on right now. Thanks for the report.

**Comment by falsechicken** [comment]
This issue was fixed in the latest beta.
