### ISSUE TITLE
Zaupshop /buy is not working!

### ISSUE THREAD

**Issue by lightphoenix2** [RocketFoundation/Rocket#83]
When updated to the latest rocket, command not working.

The "/jail add playername time cell" is also not working for https://dev.rocket.foundation/plugins/jailtime/?download=1.0.1.0

And Rocket /give, usually they will put Server have given you item. But it is now omitted. 
same goes for the commands by rocket like /kick /ban

**Comment by Zamirathe** [comment]
I'll look into it.
