### ISSUE TITLE
Plugins won't load

### ISSUE THREAD

**Issue by Flerp** [RocketFoundation/Rocket#87]
Plugins not loading with beta build #265 on Unturned 3.9.9.5

Edit: Should say commands won't load, plugins show as loaded in the console, but typing help or trying to use any commands from the plugins yields no results.

Edit #2: Disregard, just hadn't updated since API change and needed to update plugins. 

tl;dr nevermind I'm stupid

**Comment by fr34kyn01535** [comment]
One question, does it show errors for the plugins not being loaded?

**Comment by trivera90** [comment]
No errors, says the plugins are loaded but when i try to use a command from the plugin it says failed to find command.
