### ISSUE TITLE
The new "string[] command" doesn't work like the Parser.getComponentsFromSerial split does.

### ISSUE THREAD

**Issue by cartman-2000** [RocketFoundation/Rocket#88]
This doesn't advance the index of the array for a value that is empty. Like if you did a command with /2 (for optional name search and pagination.) it will only return an array with one element instead of two like it would if you used the Parser.getComponentsFromSerial function, the empty parts of it are ignored.

Of plugins that I could think of that this could effect, the global ban one comes to mind, if the reason was left off, than the duration, if one is set, would be set as the reason of the ban.

Also this causes a lot more problems than how it was done previously, there's no way to control how the string is split into an array, which means that things other than a forward slash can cause it to split.

**Comment by Zamirathe** [comment]
With the latest build, it is now a space that is the split between parts of a command.  So /i tomato 1 will give you one tomato seed.  If you need to use spaces in a phrase, just encase it in quotes.  /i "military ammunition" 3.

This doesn't keep you from using the Parser.getComponentsFromSerial in your own plugins to break it down further if you want.  I use it for my shop command in my shop plugin.  /shop add v.1 1000 will add vehicle id 1 with cost of 1000 to the shop.

**Comment by cartman-2000** [comment]
Quotes won't actually help to keep it from splitting if you use punctuation in the string you are trying to enter, like doing "test, test" would split.

**Comment by fr34kyn01535** [comment]
Fixed in lates beta #b266

**Comment by cartman-2000** [comment]
In my experience as being admin on a few different server's over the years, is that it's not a good idea to mix the types of formatting of commands. As it is now the rocket commands would have a different format compared to the in-built one, which would cause confusion to people trying to use rocket. Also this update doesn't make the job of making a plugin easier for the developer, if they still want to support the support the in-built style of using / for parameter splitting in their plugin. And in the case that the plugin developer wants to support the usage of a forward slash as the separator, you would still need to use quotes around the whole set of params to be passed to the plugin command, if any part of the command contains a space.

**Comment by fr34kyn01535** [comment]
Removing the slash as a seperator was a step forward. I do agree, while it's a bad idea to have a mixed setup - i will keep the way i changed it. Not having to worry about this is a great help for developers, and people are used to see this- coming from Minecraft eg. Going forward with Rocket i don't wan't to stick with things we are "used" from vanilla, but make it better. If you think this is a bad change i am sorry, i wont revert to the slashy solution.
