### ISSUE TITLE
Commands arent convenient anymore

### ISSUE THREAD

**Issue by ObliviousK9** [RocketFoundation/Rocket#91]
So i used to be able to do "/i maple pillar" and then bam id get it..or i could do "/i maple pillar/10" and id get 10 of them. now i HAVE to use id's or else it says invalid parameter. now i dont know if there was a set up for this ability. but its really hard to do trades on the server quickly without this convenient ability. is there ANY possible way you can get this back into the rocket system?? Please?

**Comment by fr34kyn01535** [comment]
/i "maple pillar" 10
Such convenient, Much wow

**Comment by ObliviousK9** [comment]
well its the first thing i typed in order to test it out. All im asking is if theres another way to type the command in using just the name. i can use one worded items just fine. but when it contains a space...it just gives me "invalid parameter" i dont really have patience to be mocked.

**Comment by fr34kyn01535** [comment]
I answered this question atleast 10 times today in here and on the forums... I keep this issue open so that others can see the answer.

**Comment by ObliviousK9** [comment]
Well im sorry. ill look for it then

**Comment by ObliviousK9** [comment]
Can i know the title of the issue? or at least the link?

**Comment by fr34kyn01535** [comment]
? I already answered your question, use quotes

**Comment by ObliviousK9** [comment]
OHH  jesus im so sorry. i didnt get it

**Comment by cartman-2000** [comment]
You can also use item ID's on the command, if you can remember them, you don't need to use quotes in the command for those. This is what I use for commonly spawned stuff on the server, there's less to type out using item ID.

**Comment by ObliviousK9** [comment]
Uhh has the format changed for the newest update? because i cant seem to get things spawned in?

**Comment by cartman-2000** [comment]
There was a bug with using names in the item commands for a time earlier, but that is now fixed in the latest versions of rocket mod.
