### ISSUE TITLE
UCONOMY

### ISSUE THREAD

**Issue by ObliviousK9** [RocketFoundation/Rocket#92]
Ok..so i get that this isnt a bug. But there is literally no one else that can help me with this...whatsoever.  How do i set up shop? Like...how do i get this complicated mySQL thing to work for uconomy. no one will help at all..and there arent any forums. Please..somebody help out? at least give me something

**Comment by Zamirathe** [comment]
Please read.  I already provided a starting point in a search for mysql help.
https://rocket.foundation/viewtopic.php?f=7&t=149
