### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by ObliviousK9** [RocketFoundation/Rocket#94]
Items come up as NULL for literally anything. When i spawn things in using the item id it just says (giving 1x NULL) and when i try to use the word of the item itself. it just comes up as invalid parameter. even with the new format.

**Comment by LazyPiggyHD** [comment]
yep. same here 

professional server owner buddies ftw xD

**Comment by ObliviousK9** [comment]
Aww man. I wonder when itll get fixed.

**Comment by LazyPiggyHD** [comment]
ikr. atleast it actually spawns you the item, and you cant spawn items anymore with names like /i g36 q_q

**Comment by ObliviousK9** [comment]
yeah but the thing is my server is a modded server. so when i spawn things in to trade with other players. i have to pull up the other steam page that has the id's for the modded gun. and like its hard to find EVERY SINGLE gun that they are asking for

**Comment by LazyPiggyHD** [comment]
ikr. it sucks

also what host do you use for unturned?

**Comment by ObliviousK9** [comment]
oh i made it :P

**Comment by LazyPiggyHD** [comment]
cool so did i, but i want mine to be 24/7 for my fams. q_q join if you want maximumpvp.us.to:27105

**Comment by Ev1dentFir3** [comment]
Yep same here, ID works, but name comes up as null.

**Comment by Ev1dentFir3** [comment]
@ObliviousK9 @LazyPiggyHD I also run my server from home, currently on a mac mini i5 16GB, the mac mini's use so little power it ok to run 24/7 lol

**Comment by Zamirathe** [comment]
Should be fixed with latest beta build.

**Comment by Ev1dentFir3** [comment]
Great!
