### ISSUE TITLE
PVE is actually PVP and items dont spawn in at all on PVP or PVE

### ISSUE THREAD

**Issue by mryan04290** [RocketFoundation/Rocket#95]
problem 1]I started up my PVE server normally (after updating to 3.10.0.0) and all of a sudden I started getting messages saying "The PVE server is broken we can kill each other!" so naturally I shut down the server and went to check commands.dat and everything checked out it still said PVE so I rewrote the file and started it and had the same problem, not sure if Unturned bug or rocket? 

Problem 2] /i will not work even if I use " it spits our "Invalid Parameter" so I did /i 254 and in the logs it gave me "[Error] An error occured while executing command /i 254: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Commands.CommandI.Execute (Rocket.RocketAPI.RocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0 
  at Rocket.RocketAPI.RocketCommandBase.execute (CSteamID caller, System.String command) [0x00000]  "

I'm 99.9999% I have everything written right but I'll Triple check again!

**Comment by Zamirathe** [comment]
Both of these issues should be fixed now.  Please update to latest Rocket Beta.
