### ISSUE TITLE
Exception when you try to Inventory.Clear a player on RocketServerEvents.OnPlayerConnected

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#96]
private void RocketServerEvents_OnPlayerConnected(RocketPlayer player)
{
         player.Inventory.Clear();
}

--------------------------------------------------------------------------------------------------------------------------

Exception in Log: System.NullReferenceException: Object reference not set to an instance of an object
        at Rocket.RocketAPI.PlayerInventoryExtension.Clear (SDG.PlayerInventory inventory) [0x00000] in <filename unknown>:0

**Comment by fr34kyn01535** [comment]
True, i moved the OnPlayerConnected to be executed a lil later, try it now!

**Comment by manuelbarbosa** [comment]
perfect :) close it
