### ISSUE TITLE
Got this message on the last Rocket Version now

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketFoundation/Rocket#97]
Unable to read VR Path Registry from C:\Users\Manuel Barbosa\AppData\Local\openvr\openvrpaths.vrpath

Right after he made all the config settings (password, port etc) successfully but before loading the plugins.

**Comment by fr34kyn01535** [comment]
No error at all, you get this message also when running vanilla Unturned - since we are not using VR its no big deal ;D
