### ISSUE TITLE
Bug with using empty params in commands.

### ISSUE THREAD

**Issue by cartman-2000** [RocketFoundation/Rocket#98]
There's a bug with the param's that will cause an empty param to return with a single space if the next param had quotes around it.

Testing a bans replacement plugin that I wrote for my server on a test server, with debugging stuff added in to show the space returned. This is what it returns in the console.
```
>ban "" test
name before.
name before in if.
""
1
Error: Invalid player name in ban command.
>ban "" "test"
name before.
name before in if.
" "
name after in if.
name after.
Can't find a player by the name of  , that has played on the server before.
```

**Comment by Zamirathe** [comment]
Why are you trying to use an empty parameter in the first place?  Unless the documentation specifically shows something as optional by surrounding it with [], it is required and will error out otherwise.

**Comment by cartman-2000** [comment]
I'm not, I just found this inconsistency when testing out and coding fail cases on the plugin. As it is now, I would have to check for both an empty string and a single space string for an empty parameter.

**Comment by Zamirathe** [comment]
Ok, good point.  I think it just easier to check if the first parameter is null, empty, or what you are looking for.  If it isn't, then return a generic invalid parameter message.

**Comment by cartman-2000** [comment]
I'm the kind of person that likes to be specific in the error cases in plugins, it means more code, but it would help the person using the plugin to know what they are doing wrong when they are trying to run the command.

**Comment by fr34kyn01535** [comment]
Testing a parameter for "" or " " is a overhead of 7 chars in developing, would not say this was a huge issue ;D (parameter[2].Trim() == String.Empty)

You are right tho, its inconsistent, if fixed that, now empty parameters are really String.Empty.
